export const quizData = [
  {
    character: '零',
    pinyin: 'líng',
    answer: 'zero',
    wrongAnswers: ['two', 'one', 'three'],
    lesson: 'Numbers',
  },
  {
    character: '一',
    pinyin: 'yī',
    answer: 'one',
    wrongAnswers: ['two', 'three', 'four'],
    lesson: 'Numbers',
  },
  {
    character: '二',
    pinyin: 'èr',
    answer: 'two',
    wrongAnswers: ['one', 'three', 'five'],
    lesson: 'Numbers',
  },
  {
    character: '三',
    pinyin: 'sān',
    answer: 'three',
    wrongAnswers: ['two', 'four', 'six'],
    lesson: 'Numbers',
  },
  {
    character: '四',
    pinyin: 'sì',
    answer: 'four',
    wrongAnswers: ['three', 'five', 'seven'],
    lesson: 'Numbers',
  },
  {
    character: '五',
    pinyin: 'wǔ',
    answer: 'five',
    wrongAnswers: ['four', 'six', 'eight'],
    lesson: 'Numbers',
  },
  {
    character: '六',
    pinyin: 'liù',
    answer: 'six',
    wrongAnswers: ['five', 'seven', 'nine'],
    lesson: 'Numbers',
  },
  {
    character: '七',
    pinyin: 'qī',
    answer: 'seven',
    wrongAnswers: ['six', 'eight', 'ten'],
    lesson: 'Numbers',
  },
  {
    character: '八',
    pinyin: 'bā',
    answer: 'eight',
    wrongAnswers: ['seven', 'nine', 'eleven'],
    lesson: 'Numbers',
  },
  {
    character: '九',
    pinyin: 'jiǔ',
    answer: 'nine',
    wrongAnswers: ['eight', 'ten', 'twelve'],
    lesson: 'Numbers',
  },
  {
    character: '十',
    pinyin: 'shí',
    answer: 'ten',
    wrongAnswers: ['nine', 'eleven', 'twenty'],
    lesson: 'Numbers',
  },
  {
    character: '我',
    pinyin: 'wǒ',
    answer: 'I/me',
    wrongAnswers: ['you', 'he/she', 'we'],
    lesson: 'Pronouns',
  },
  {
    character: '你',
    pinyin: 'nǐ',
    answer: 'you',
    wrongAnswers: ['I', 'we', 'they'],
    lesson: 'Pronouns',
  },
  {
    character: '他',
    pinyin: 'tā',
    answer: 'he/him',
    wrongAnswers: ['she/her', 'it', 'you'],
    lesson: 'Pronouns',
  },
  {
    character: '她',
    pinyin: 'tā',
    answer: 'she/her',
    wrongAnswers: ['he/him', 'it', 'you'],
    lesson: 'Pronouns',
  },
  {
    character: '我们',
    pinyin: 'wǒmen',
    answer: 'we/us',
    wrongAnswers: ['you', 'they/them', 'I/me'],
    lesson: 'Pronouns',
  },
  {
    character: '这/这儿',
    pinyin: 'zhè/zhèr',
    answer: 'this/here',
    wrongAnswers: ['that/there', 'it/there', 'these/there'],
    lesson: 'Pronouns',
  },
  {
    character: '那/那儿',
    pinyin: 'nà/nàr',
    answer: 'that/there',
    wrongAnswers: ['this/here', 'it/here', 'those/here'],
    lesson: 'Pronouns',
  },
  {
    character: '哪/哪儿',
    pinyin: 'nǎ/nǎr',
    answer: 'which/where',
    wrongAnswers: ['who', 'what', 'how'],
    lesson: 'Interrogative',
  },
  {
    character: '谁',
    pinyin: 'shéi',
    answer: 'who',
    wrongAnswers: ['which', 'what', 'how'],
    lesson: 'Interrogative',
  },
  {
    character: '什么',
    pinyin: 'shénme',
    answer: 'what',
    wrongAnswers: ['who', 'which', 'how'],
    lesson: 'Interrogative',
  },
  {
    character: '多少',
    pinyin: 'duōshao',
    answer: 'how many or how much',
    wrongAnswers: ['where', 'what', 'how'],
    lesson: 'Interrogative',
  },
  {
    character: '几',
    pinyin: 'jǐ',
    answer: 'how many or how much',
    wrongAnswers: ['which', 'what', 'how'],
    lesson: 'Interrogative',
  },
  {
    character: '怎么',
    pinyin: 'zěnme',
    answer: 'how',
    wrongAnswers: ['where', 'what', 'who'],
    lesson: 'Interrogative',
  },
  {
    character: '怎么样',
    pinyin: 'zěnmeyàng',
    answer: 'how about',
    wrongAnswers: ['what', 'how', 'who'],
    lesson: 'Interrogative',
  },
  {
    character: '现在',
    pinyin: 'xiànzài',
    answer: 'now',
    wrongAnswers: ['today', 'tomorrow', 'yesterday'],
    lesson: 'Time',
  },
  {
    character: '今天',
    pinyin: 'jīntiān',
    answer: 'today',
    wrongAnswers: ['now', 'tomorrow', 'yesterday'],
    lesson: 'Time',
  },
  {
    character: '明天',
    pinyin: 'míngtiān',
    answer: 'tomorrow',
    wrongAnswers: ['now', 'today', 'yesterday'],
    lesson: 'Time',
  },
  {
    character: '昨天',
    pinyin: 'zuótiān',
    answer: 'yesterday',
    wrongAnswers: ['now', 'today', 'tomorrow'],
    lesson: 'Time',
  },
  {
    character: '上午',
    pinyin: 'shàngwǔ',
    answer: 'morning',
    wrongAnswers: ['noon', 'afternoon', 'week'],
    lesson: 'Time',
  },
  {
    character: '中午',
    pinyin: 'zhōngwǔ',
    answer: 'noon',
    wrongAnswers: ['morning', 'afternoon', 'week'],
    lesson: 'Time',
  },
  {
    character: '下午',
    pinyin: 'xiàwǔ',
    answer: 'afternoon',
    wrongAnswers: ['morning', 'noon', 'week'],
    lesson: 'Time',
  },
  {
    character: '点',
    pinyin: 'diǎn',
    answer: 'o’clock',
    wrongAnswers: ['minute', 'hour', 'now'],
    lesson: 'Time',
  },
  {
    character: '分钟',
    pinyin: 'fēnzhōng',
    answer: 'minute',
    wrongAnswers: ['o’clock', 'hour', 'now'],
    lesson: 'Time',
  },
  {
    character: '年',
    pinyin: 'nián',
    answer: 'year',
    wrongAnswers: ['month', 'day', 'week'],
    lesson: 'Time',
  },
  {
    character: '月',
    pinyin: 'yuè',
    answer: 'month',
    wrongAnswers: ['year', 'day', 'week'],
    lesson: 'Time',
  },
  {
    character: '日',
    pinyin: 'rì',
    answer: 'day',
    wrongAnswers: ['year', 'month', 'week'],
    lesson: 'Time',
  },
  {
    character: '星期',
    pinyin: 'xīngqī',
    answer: 'week',
    wrongAnswers: ['year', 'month', 'day'],
    lesson: 'Time',
  },
  {
    character: '时候',
    pinyin: 'shíhou',
    answer: 'a certain point in time',
    wrongAnswers: ['now', 'today', 'tomorrow'],
    lesson: 'Time',
  },
  {
    character: '人',
    pinyin: 'rén',
    answer: 'person or people',
    wrongAnswers: ['name', 'water', 'book'],
    lesson: 'People and Things',
  },
  {
    character: '名字',
    pinyin: 'míngzì',
    answer: 'name',
    wrongAnswers: ['person', 'teacher', 'money'],
    lesson: 'People and Things',
  },
  {
    character: '妈妈',
    pinyin: 'māma',
    answer: 'mom',
    wrongAnswers: ['dad', 'son', 'daughter'],
    lesson: 'People and Things',
  },
  {
    character: '爸爸',
    pinyin: 'bàba',
    answer: 'dad',
    wrongAnswers: ['mom', 'son', 'daughter'],
    lesson: 'People and Things',
  },
  {
    character: '儿子',
    pinyin: 'érzi',
    answer: 'son',
    wrongAnswers: ['daughter', 'friend', 'student'],
    lesson: 'People and Things',
  },
  {
    character: '女儿',
    pinyin: 'nǚ’ér',
    answer: 'daughter',
    wrongAnswers: ['son', 'friend', 'student'],
    lesson: 'People and Things',
  },
  {
    character: '朋友',
    pinyin: 'péngyǒu',
    answer: 'friend',
    wrongAnswers: ['teacher', 'book', 'water'],
    lesson: 'People and Things',
  },
  {
    character: '先生',
    pinyin: 'xiānsheng',
    answer: 'Mr or sir',
    wrongAnswers: ['Miss', 'teacher', 'student'],
    lesson: 'People and Things',
  },
  {
    character: '小姐',
    pinyin: 'xiǎojiě',
    answer: 'Miss',
    wrongAnswers: ['Mr', 'teacher', 'student'],
    lesson: 'People and Things',
  },
  {
    character: '老师',
    pinyin: 'lǎoshī',
    answer: 'teacher',
    wrongAnswers: ['friend', 'cat', 'book'],
    lesson: 'People and Things',
  },
  {
    character: '学生',
    pinyin: 'xuésheng',
    answer: 'student',
    wrongAnswers: ['teacher', 'dog', 'apple'],
    lesson: 'People and Things',
  },
  {
    character: '同学',
    pinyin: 'tóngxué',
    answer: 'schoolmate',
    wrongAnswers: ['friend', 'teacher', 'book'],
    lesson: 'People and Things',
  },
  {
    character: '医生',
    pinyin: 'yīshēng',
    answer: 'doctor',
    wrongAnswers: ['teacher', 'fruit', 'water'],
    lesson: 'People and Things',
  },
  {
    character: '东西',
    pinyin: 'dōngxi',
    answer: 'thing',
    wrongAnswers: ['book', 'apple', 'dog'],
    lesson: 'People and Things',
  },
  {
    character: '钱',
    pinyin: 'qián',
    answer: 'money',
    wrongAnswers: ['cup', 'year', 'friend'],
    lesson: 'People and Things',
  },
  {
    character: '水',
    pinyin: 'shuǐ',
    answer: 'water',
    wrongAnswers: ['dog', 'book', 'teacher'],
    lesson: 'People and Things',
  },
  {
    character: '茶',
    pinyin: 'chá',
    answer: 'tea',
    wrongAnswers: ['apple', 'money', 'book'],
    lesson: 'People and Things',
  },
  {
    character: '菜',
    pinyin: 'cài',
    answer: 'dish',
    wrongAnswers: ['dog', 'year', 'friend'],
    lesson: 'People and Things',
  },
  {
    character: '米饭',
    pinyin: 'mǐfàn',
    answer: '(cooked) rice',
    wrongAnswers: ['cat', 'apple', 'dog'],
    lesson: 'People and Things',
  },
  {
    character: '衣服',
    pinyin: 'yīfu',
    answer: 'clothes',
    wrongAnswers: ['book', 'cup', 'water'],
    lesson: 'People and Things',
  },
  {
    character: '书',
    pinyin: 'shū',
    answer: 'book',
    wrongAnswers: ['money', 'apple', 'cat'],
    lesson: 'People and Things',
  },
  {
    character: '桌子',
    pinyin: 'zhuōzi',
    answer: 'table or desk',
    wrongAnswers: ['chair', 'dog', 'book'],
    lesson: 'People and Things',
  },
  {
    character: '椅子',
    pinyin: 'yǐzi',
    answer: 'chair',
    wrongAnswers: ['table', 'desk', 'bed'],
    lesson: 'People and Things',
  },
  {
    character: '水果',
    pinyin: 'shuǐguǒ',
    answer: 'fruit',
    wrongAnswers: ['vegetable', 'meat', 'bread'],
    lesson: 'People and Things',
  },
  {
    character: '苹果',
    pinyin: 'píngguǒ',
    answer: 'apple',
    wrongAnswers: ['banana', 'orange', 'grape'],
    lesson: 'People and Things',
  },
  {
    character: '杯子',
    pinyin: 'bēizi',
    answer: 'cup or glass',
    wrongAnswers: ['plate', 'bowl', 'fork'],
    lesson: 'People and Things',
  },
  {
    character: '电视',
    pinyin: 'diànshì',
    answer: 'TV',
    wrongAnswers: ['radio', 'computer', 'phone'],
    lesson: 'People and Things',
  },
  {
    character: '电脑',
    pinyin: 'diànnǎo',
    answer: 'computer',
    wrongAnswers: ['printer', 'scanner', 'keyboard'],
    lesson: 'People and Things',
  },
  {
    character: '电影',
    pinyin: 'diànyǐng',
    answer: 'movie',
    wrongAnswers: ['book', 'music', 'painting'],
    lesson: 'People and Things',
  },
  {
    character: '飞机',
    pinyin: 'fēijī',
    answer: 'plane',
    wrongAnswers: ['car', 'boat', 'train'],
    lesson: 'People and Things',
  },
  {
    character: '出租车',
    pinyin: 'chūzūchē',
    answer: 'taxi',
    wrongAnswers: ['bus', 'bike', 'subway'],
    lesson: 'People and Things',
  },
  {
    character: '猫',
    pinyin: 'māo',
    answer: 'cat',
    wrongAnswers: ['dog', 'bird', 'fish'],
    lesson: 'People and Things',
  },
  {
    character: '狗',
    pinyin: 'gǒu',
    answer: 'dog',
    wrongAnswers: ['cat', 'horse', 'rabbit'],
    lesson: 'People and Things',
  },
  {
    character: '天气',
    pinyin: 'tiānqì',
    answer: 'weather',
    wrongAnswers: ['time', 'season', 'temperature'],
    lesson: 'People and Things',
  },
  {
    character: '字',
    pinyin: 'zì',
    answer: 'character',
    wrongAnswers: ['word', 'letter', 'symbol'],
    lesson: 'People and Things',
  },
  {
    character: '汉语',
    pinyin: 'Hànyǔ',
    answer: 'Chinese (language)',
    wrongAnswers: ['English', 'Spanish', 'French'],
    lesson: 'People and Things',
  },
  {
    character: '中国',
    pinyin: 'Zhōngguó',
    answer: 'China',
    wrongAnswers: ['Japan', 'Korea', 'India'],
    lesson: 'Places and Directions',
  },
  {
    character: '北京',
    pinyin: 'Běijīng',
    answer: 'Beijing',
    wrongAnswers: ['Shanghai', 'Guangzhou', 'Hong Kong'],
    lesson: 'Places and Directions',
  },
  {
    character: '家',
    pinyin: 'jiā',
    answer: 'home or family',
    wrongAnswers: ['school', 'restaurant', 'hospital'],
    lesson: 'Places and Directions',
  },
  {
    character: '学校',
    pinyin: 'xuéxiào',
    answer: 'school',
    wrongAnswers: ['shop', 'restaurant', 'hospital'],
    lesson: 'Places and Directions',
  },
  {
    character: '饭馆',
    pinyin: 'fànguǎn',
    answer: 'restaurant',
    wrongAnswers: ['shop', 'school', 'hospital'],
    lesson: 'Places and Directions',
  },
  {
    character: '商店',
    pinyin: 'shāngdiàn',
    answer: 'shop',
    wrongAnswers: ['restaurant', 'school', 'hospital'],
    lesson: 'Places and Directions',
  },
  {
    character: '医院',
    pinyin: 'yīyuàn',
    answer: 'hospital',
    wrongAnswers: ['shop', 'school', 'restaurant'],
    lesson: 'Places and Directions',
  },
  {
    character: '火车站',
    pinyin: 'huǒchēzhàn',
    answer: 'train station',
    wrongAnswers: ['airport', 'bus stop', 'subway station'],
    lesson: 'Places and Directions',
  },
  {
    character: '上',
    pinyin: 'shàng',
    answer: 'on, above or last',
    wrongAnswers: ['under, below', 'next', 'inside'],
    lesson: 'Places and Directions',
  },
  {
    character: '下',
    pinyin: 'xià',
    answer: 'under, below or next',
    wrongAnswers: ['on, above', 'last', 'inside'],
    lesson: 'Places and Directions',
  },
  {
    character: '前面',
    pinyin: 'qiánmiàn',
    answer: 'front',
    wrongAnswers: ['back', 'inside', 'side'],
    lesson: 'Places and Directions',
  },
  {
    character: '后面',
    pinyin: 'hòumiàn',
    answer: 'back',
    wrongAnswers: ['front', 'inside', 'side'],
    lesson: 'Places and Directions',
  },
  {
    character: '里',
    pinyin: 'lǐ',
    answer: 'inside',
    wrongAnswers: ['outside', 'near', 'far'],
    lesson: 'Places and Directions',
  },

  {
    character: '个',
    pinyin: 'gè',
    answer: 'generic measure word',
    wrongAnswers: ['big', 'small', 'round'],
    lesson: 'Measure Words',
  },
  {
    character: '块',
    pinyin: 'kuài',
    answer: 'basic monetary unit of China',
    wrongAnswers: ['coin', 'note', 'dollar'],
    lesson: 'Measure Words',
  },
  {
    character: '本',
    pinyin: 'běn',
    answer: 'for books',
    wrongAnswers: ['for food', 'for clothes', 'for electronics'],
    lesson: 'Measure Words',
  },
  {
    character: '岁',
    pinyin: 'suì',
    answer: 'year (of age)',
    wrongAnswers: ['month', 'day', 'hour'],
    lesson: 'Measure Words',
  },
  {
    character: '些',
    pinyin: 'xiē',
    answer: 'some',
    wrongAnswers: ['many', 'few', 'all'],
    lesson: 'Measure Words',
  },
  {
    character: '做',
    pinyin: 'zuò',
    answer: 'to do',
    wrongAnswers: ['to eat', 'to go', 'to come'],
    lesson: 'Verbs',
  },
  {
    character: '是',
    pinyin: 'shì',
    answer: 'to be',
    wrongAnswers: ['to do', 'to have', 'to go'],
    lesson: 'Verbs',
  },
  {
    character: '在',
    pinyin: 'zài',
    answer: 'to be in',
    wrongAnswers: ['to do', 'to have', 'to go'],
    lesson: 'Verbs',
  },
  {
    character: '有',
    pinyin: 'yǒu',
    answer: 'to have',
    wrongAnswers: ['to be', 'to do', 'to go'],
    lesson: 'Verbs',
  },
  {
    character: '住',
    pinyin: 'zhù',
    answer: 'to live or to stay',
    wrongAnswers: ['to eat', 'to go', 'to come'],
    lesson: 'Verbs',
  },
  {
    character: '来',
    pinyin: 'lái',
    answer: 'to come',
    wrongAnswers: ['to go', 'to do', 'to have'],
    lesson: 'Verbs',
  },
  {
    character: '去',
    pinyin: 'qù',
    answer: 'to go',
    wrongAnswers: ['to come', 'to do', 'to be'],
    lesson: 'Verbs',
  },
  {
    character: '回',
    pinyin: 'huí',
    answer: 'to return',
    wrongAnswers: ['to go', 'to come', 'to do'],
    lesson: 'Verbs',
  },
  {
    character: '想',
    pinyin: 'xiǎng',
    answer: 'to think',
    wrongAnswers: ['to eat', 'to go', 'to come'],
    lesson: 'Verbs',
  },
  {
    character: '吃',
    pinyin: 'chī',
    answer: 'to eat',
    wrongAnswers: ['to do', 'to go', 'to come'],
    lesson: 'Verbs',
  },
  {
    character: '喝',
    pinyin: 'hē',
    answer: 'to drink',
    wrongAnswers: ['to eat', 'to sleep', 'to talk'],
    lesson: 'Verbs',
  },
  {
    character: '说话',
    pinyin: 'shuōhuà',
    answer: 'to speak',
    wrongAnswers: ['to read', 'to listen', 'to buy'],
    lesson: 'Verbs',
  },
  {
    character: '看',
    pinyin: 'kàn',
    answer: 'to look or to watch',
    wrongAnswers: ['to eat', 'to drive', 'to read'],
    lesson: 'Verbs',
  },
  {
    character: '看见',
    pinyin: 'kànjiàn',
    answer: 'to see',
    wrongAnswers: ['to read', 'to listen', 'to buy'],
    lesson: 'Verbs',
  },
  {
    character: '听',
    pinyin: 'tīng',
    answer: 'to listen',
    wrongAnswers: ['to speak', 'to drive', 'to buy'],
    lesson: 'Verbs',
  },
  {
    character: '叫',
    pinyin: 'jiào',
    answer: 'to call',
    wrongAnswers: ['to sit', 'to open', 'to drink'],
    lesson: 'Verbs',
  },
  {
    character: '买',
    pinyin: 'mǎi',
    answer: 'to buy',
    wrongAnswers: ['to drive', 'to sit', 'to open'],
    lesson: 'Verbs',
  },
  {
    character: '开',
    pinyin: 'kāi',
    answer: 'to drive or to open',
    wrongAnswers: ['to buy', 'to sit', 'to drink'],
    lesson: 'Verbs',
  },
  {
    character: '坐',
    pinyin: 'zuò',
    answer: 'to sit',
    wrongAnswers: ['to drink', 'to drive', 'to read'],
    lesson: 'Verbs',
  },
  {
    character: '读',
    pinyin: 'dú',
    answer: 'to read',
    wrongAnswers: ['to listen', 'to watch', 'to buy'],
    lesson: 'Verbs',
  },
  {
    character: '写',
    pinyin: 'xiě',
    answer: 'to write',
    wrongAnswers: ['to read', 'to learn', 'to work'],
    lesson: 'Verbs',
  },
  {
    character: '打电话',
    pinyin: 'dǎ diànhuà',
    answer: 'to make a phone call',
    wrongAnswers: ['to write', 'to learn', 'to work'],
    lesson: 'Verbs',
  },
  {
    character: '认识',
    pinyin: 'rènshi',
    answer: 'to know',
    wrongAnswers: ['to learn', 'to work', 'to write'],
    lesson: 'Verbs',
  },
  {
    character: '学习',
    pinyin: 'xuéxí',
    answer: 'to learn',
    wrongAnswers: ['to write', 'to know', 'to work'],
    lesson: 'Verbs',
  },
  {
    character: '工作',
    pinyin: 'gōngzuò',
    answer: 'to work',
    wrongAnswers: ['to learn', 'to know', 'to write'],
    lesson: 'Verbs',
  },
  {
    character: '睡觉',
    pinyin: 'shuìjiào',
    answer: 'to sleep',
    wrongAnswers: ['to work', 'to learn', 'to write'],
    lesson: 'Verbs',
  },
  {
    character: '喜欢',
    pinyin: 'xǐhuan',
    answer: 'to like',
    wrongAnswers: ['to love', 'to know', 'to work'],
    lesson: 'Verbs',
  },
  {
    character: '爱',
    pinyin: 'ài',
    answer: 'to love',
    wrongAnswers: ['to like', 'to know', 'to work'],
    lesson: 'Verbs',
  },
  {
    character: '会',
    pinyin: 'huì',
    answer: 'can (to know how to)',
    wrongAnswers: ['to be able to', 'to learn', 'to work'],
    lesson: 'Verbs',
  },
  {
    character: '能',
    pinyin: 'néng',
    answer: 'can (to be able to)',
    wrongAnswers: ['to know', 'to learn', 'to work'],
    lesson: 'Verbs',
  },
  {
    character: '下雨',
    pinyin: 'xià yǔ',
    answer: 'to rain',
    wrongAnswers: ['to snow', 'to shine', 'to be windy'],
    lesson: 'Verbs',
  },
  {
    character: '好',
    pinyin: 'hǎo',
    answer: 'good',
    wrongAnswers: ['bad', 'big', 'small'],
    lesson: 'Adjectives and Adverbs',
  },
  {
    character: '大',
    pinyin: 'dà',
    answer: 'big',
    wrongAnswers: ['small', 'good', 'bad'],
    lesson: 'Adjectives and Adverbs',
  },
  {
    character: '小',
    pinyin: 'xiǎo',
    answer: 'small',
    wrongAnswers: ['big', 'good', 'bad'],
    lesson: 'Adjectives and Adverbs',
  },
  {
    character: '多',
    pinyin: 'duō',
    answer: 'many',
    wrongAnswers: ['few', 'big', 'small'],
    lesson: 'Adjectives and Adverbs',
  },
  {
    character: '少',
    pinyin: 'shǎo',
    answer: 'few',
    wrongAnswers: ['many', 'big', 'small'],
    lesson: 'Adjectives and Adverbs',
  },
  {
    character: '热',
    pinyin: 'rè',
    answer: 'hot',
    wrongAnswers: ['cold', 'good', 'bad'],
    lesson: 'Adjectives and Adverbs',
  },
  {
    character: '冷',
    pinyin: 'lěng',
    answer: 'cold',
    wrongAnswers: ['hot', 'good', 'bad'],
    lesson: 'Adjectives and Adverbs',
  },
  {
    character: '漂亮',
    pinyin: 'piàoliang',
    answer: 'pretty',
    wrongAnswers: ['ugly', 'beautiful', 'good'],
    lesson: 'Adjectives and Adverbs',
  },
  {
    character: '高兴',
    pinyin: 'gāoxìng',
    answer: 'happy',
    wrongAnswers: ['sad', 'excited', 'good'],
    lesson: 'Adjectives and Adverbs',
  },
  {
    character: '很',
    pinyin: 'hěn',
    answer: 'very',
    wrongAnswers: ['too', 'a lot', 'little'],
    lesson: 'Adjectives and Adverbs',
  },
  {
    character: '太',
    pinyin: 'tài',
    answer: 'too…',
    wrongAnswers: ['very', 'a lot', 'little'],
    lesson: 'Adjectives and Adverbs',
  },
  {
    character: '都',
    pinyin: 'dōu',
    answer: 'both or all',
    wrongAnswers: ['neither', 'only', 'some'],
    lesson: 'Adjectives and Adverbs',
  },
  {
    character: '不',
    pinyin: 'bù',
    answer: 'not',
    wrongAnswers: ['yes', 'no', 'maybe'],
    lesson: 'Adjectives and Adverbs',
  },
  {
    character: '没',
    pinyin: 'méi',
    answer: 'not',
    wrongAnswers: ['yes', 'no', 'maybe'],
    lesson: 'Adjectives and Adverbs',
  },
  {
    character: '喂',
    pinyin: 'wèi',
    answer: 'hello (on the phone)',
    wrongAnswers: ['thanks', 'goodbye', 'please'],
    lesson: 'Expressions',
  },
  {
    character: '谢谢',
    pinyin: 'xièxie',
    answer: 'thanks',
    wrongAnswers: ['hello', 'you’re welcome', 'please'],
    lesson: 'Expressions',
  },
  {
    character: '不客气',
    pinyin: 'bú kèqi',
    answer: 'you’re welcome',
    wrongAnswers: ['thanks', 'it’s all right', 'please'],
    lesson: 'Expressions',
  },
  {
    character: '再见',
    pinyin: 'zàijiàn',
    answer: 'goodbye',
    wrongAnswers: ['hello', 'thanks', 'please'],
    lesson: 'Expressions',
  },
  {
    character: '请',
    pinyin: 'qǐng',
    answer: 'please…',
    wrongAnswers: ['hello', 'thanks', 'goodbye'],
    lesson: 'Expressions',
  },
  {
    character: '对不起',
    pinyin: 'duìbuqǐ',
    answer: 'sorry',
    wrongAnswers: ['hello', 'thanks', 'goodbye'],
    lesson: 'Expressions',
  },
  {
    character: '没关系',
    pinyin: 'méi guānxi',
    answer: 'it’s all right',
    wrongAnswers: ['you’re welcome', 'thanks', 'sorry'],
    lesson: 'Expressions',
  },
];
