export const quizData = [
  {
    character: '零',
    pinyin: 'líng',
    answer: 'zero',
    wrongAnswers: ['two', 'one', 'three'],
    topic: 'Numbers',
    lesson: '5',
  },
  {
    character: '一',
    pinyin: 'yī',
    answer: 'one',
    wrongAnswers: ['two', 'three', 'four'],
    topic: 'Numbers',
    lesson: '5',
  },
  {
    character: '二',
    pinyin: 'èr',
    answer: 'two',
    wrongAnswers: ['one', 'three', 'five'],
    topic: 'Numbers',
    lesson: '5',
  },
  {
    character: '三',
    pinyin: 'sān',
    answer: 'three',
    wrongAnswers: ['two', 'four', 'six'],
    topic: 'Numbers',
    lesson: '5',
  },
  {
    character: '四',
    pinyin: 'sì',
    answer: 'four',
    wrongAnswers: ['three', 'five', 'seven'],
    topic: 'Numbers',
    lesson: '5',
  },
  {
    character: '五',
    pinyin: 'wǔ',
    answer: 'five',
    wrongAnswers: ['four', 'six', 'eight'],
    topic: 'Numbers',
    lesson: '5',
  },
  {
    character: '六',
    pinyin: 'liù',
    answer: 'six',
    wrongAnswers: ['five', 'seven', 'nine'],
    topic: 'Numbers',
    lesson: '5',
  },
  {
    character: '七',
    pinyin: 'qī',
    answer: 'seven',
    wrongAnswers: ['six', 'eight', 'ten'],
    topic: 'Numbers',
    lesson: '5',
  },
  {
    character: '八',
    pinyin: 'bā',
    answer: 'eight',
    wrongAnswers: ['seven', 'nine', 'eleven'],
    topic: 'Numbers',
    lesson: '5',
  },
  {
    character: '九',
    pinyin: 'jiǔ',
    answer: 'nine',
    wrongAnswers: ['eight', 'ten', 'twelve'],
    topic: 'Numbers',
    lesson: '5',
  },
  {
    character: '十',
    pinyin: 'shí',
    answer: 'ten',
    wrongAnswers: ['nine', 'eleven', 'twenty'],
    topic: 'Numbers',
    lesson: '5',
  },
  {
    character: '我',
    pinyin: 'wǒ',
    answer: 'I/me',
    wrongAnswers: ['you', 'he/she', 'we'],
    topic: 'Pronouns',
    lesson: '3',
  },
  {
    character: '你',
    pinyin: 'nǐ',
    answer: 'you',
    wrongAnswers: ['I', 'we', 'they'],
    topic: 'Pronouns',
    lesson: '3',
  },
  {
    character: '他',
    pinyin: 'tā',
    answer: 'he/him',
    wrongAnswers: ['she/her', 'it', 'you'],
    topic: 'Pronouns',
    lesson: '4',
  },
  {
    character: '她',
    pinyin: 'tā',
    answer: 'she/her',
    wrongAnswers: ['he/him', 'it', 'you'],
    topic: 'Pronouns',
    lesson: '4',
  },
  {
    character: '我们',
    pinyin: 'wǒmen',
    answer: 'we/us',
    wrongAnswers: ['you', 'they/them', 'I/me'],
    topic: 'Pronouns',
    lesson: '4',
  },
  {
    character: '这/这儿',
    pinyin: 'zhè/zhèr',
    answer: 'this/here',
    wrongAnswers: ['that/there', 'it/there', 'these/there'],
    topic: 'Pronouns',
    lesson: '4',
  },
  {
    character: '那/那儿',
    pinyin: 'nà/nàr',
    answer: 'that/there',
    wrongAnswers: ['this/here', 'it/here', 'those/here'],
    topic: 'Pronouns',
    lesson: '4',
  },
  {
    character: '哪/哪儿',
    pinyin: 'nǎ/nǎr',
    answer: 'which/where',
    wrongAnswers: ['who', 'what', 'how'],
    topic: 'Interrogative',
    lesson: '4',
  },
  {
    character: '谁',
    pinyin: 'shéi',
    answer: 'who',
    wrongAnswers: ['which', 'what', 'how'],
    topic: 'Interrogative',
    lesson: '4',
  },
  {
    character: '什么',
    pinyin: 'shénme',
    answer: 'what',
    wrongAnswers: ['who', 'which', 'how'],
    topic: 'Interrogative',
    lesson: '4',
  },
  {
    character: '多少',
    pinyin: 'duōshao',
    answer: 'how many or how much',
    wrongAnswers: ['where', 'what', 'how'],
    topic: 'Interrogative',
    lesson: '8',
  },
  {
    character: '几',
    pinyin: 'jǐ',
    answer: 'how many or how much',
    wrongAnswers: ['which', 'what', 'how'],
    topic: 'Interrogative',
    lesson: '5',
  },
  {
    character: '怎么',
    pinyin: 'zěnme',
    answer: 'how',
    wrongAnswers: ['where', 'what', 'who'],
    topic: 'Interrogative',
    lesson: '6',
  },
  {
    character: '怎么样',
    pinyin: 'zěnmeyàng',
    answer: 'how about',
    wrongAnswers: ['what', 'how', 'who'],
    topic: 'Interrogative',
    lesson: '6',
  },
  {
    character: '现在',
    pinyin: 'xiànzài',
    answer: 'now',
    wrongAnswers: ['today', 'tomorrow', 'yesterday'],
    topic: 'Date and Time',
    lesson: '7',
  },
  {
    character: '今天',
    pinyin: 'jīntiān',
    answer: 'today',
    wrongAnswers: ['now', 'tomorrow', 'yesterday'],
    topic: 'Date and Time',
    lesson: '7',
  },
  {
    character: '明天',
    pinyin: 'míngtiān',
    answer: 'tomorrow',
    wrongAnswers: ['now', 'today', 'yesterday'],
    topic: 'Date and Time',
    lesson: '7',
  },
  {
    character: '昨天',
    pinyin: 'zuótiān',
    answer: 'yesterday',
    wrongAnswers: ['now', 'today', 'tomorrow'],
    topic: 'Date and Time',
    lesson: '7',
  },
  {
    character: '上午',
    pinyin: 'shàngwǔ',
    answer: 'morning',
    wrongAnswers: ['noon', 'afternoon', 'week'],
    topic: 'Date and Time',
    lesson: '7',
  },
  {
    character: '中午',
    pinyin: 'zhōngwǔ',
    answer: 'noon',
    wrongAnswers: ['morning', 'afternoon', 'week'],
    topic: 'Date and Time',
    lesson: '7',
  },
  {
    character: '下午',
    pinyin: 'xiàwǔ',
    answer: 'afternoon',
    wrongAnswers: ['morning', 'noon', 'week'],
    topic: 'Date and Time',
    lesson: '8',
  },
  {
    character: '点',
    pinyin: 'diǎn',
    answer: 'o’clock',
    wrongAnswers: ['minute', 'hour', 'now'],
    topic: 'Date and Time',
    lesson: '7',
  },
  {
    character: '分钟',
    pinyin: 'fēnzhōng',
    answer: 'minute',
    wrongAnswers: ['o’clock', 'hour', 'now'],
    topic: 'Date and Time',
    lesson: '7',
  },
  {
    character: '年',
    pinyin: 'nián',
    answer: 'year',
    wrongAnswers: ['month', 'day', 'week'],
    topic: 'Date and Time',
    lesson: '7',
  },
  {
    character: '月',
    pinyin: 'yuè',
    answer: 'month',
    wrongAnswers: ['year', 'day', 'week'],
    topic: 'Date and Time',
    lesson: '7',
  },
  {
    character: '日',
    pinyin: 'rì',
    answer: 'day',
    wrongAnswers: ['year', 'month', 'week'],
    topic: 'Date and Time',
    lesson: '7',
  },
  {
    character: '星期',
    pinyin: 'xīngqī',
    answer: 'week',
    wrongAnswers: ['year', 'month', 'day'],
    topic: 'Date and Time',
    lesson: '7',
  },
  {
    character: '时候',
    pinyin: 'shíhou',
    answer: 'a certain point in time',
    wrongAnswers: ['now', 'today', 'tomorrow'],
    topic: 'Date and Time',
    lesson: '7',
  },
  {
    character: '人',
    pinyin: 'rén',
    answer: 'person or people',
    wrongAnswers: ['name', 'water', 'book'],
    topic: 'People and Things',
    lesson: '3',
  },
  {
    character: '名字',
    pinyin: 'míngzì',
    answer: 'name',
    wrongAnswers: ['person', 'teacher', 'money'],
    topic: 'People and Things',
    lesson: '3',
  },
  {
    character: '妈妈',
    pinyin: 'māma',
    answer: 'mom',
    wrongAnswers: ['dad', 'son', 'daughter'],
    topic: 'People and Things',
    lesson: '5',
  },
  {
    character: '爸爸',
    pinyin: 'bàba',
    answer: 'dad',
    wrongAnswers: ['mom', 'son', 'daughter'],
    topic: 'People and Things',
    lesson: '5',
  },
  {
    character: '儿子',
    pinyin: 'érzi',
    answer: 'son',
    wrongAnswers: ['daughter', 'friend', 'student'],
    topic: 'People and Things',
    lesson: '5',
  },
  {
    character: '女儿',
    pinyin: 'nǚ’ér',
    answer: 'daughter',
    wrongAnswers: ['son', 'friend', 'student'],
    topic: 'People and Things',
    lesson: '5',
  },
  {
    character: '朋友',
    pinyin: 'péngyǒu',
    answer: 'friend',
    wrongAnswers: ['teacher', 'book', 'water'],
    topic: 'People and Things',
    lesson: '3',
  },
  {
    character: '先生',
    pinyin: 'xiānsheng',
    answer: 'Mr or sir',
    wrongAnswers: ['Miss', 'teacher', 'student'],
    topic: 'People and Things',
    lesson: '3',
  },
  {
    character: '小姐',
    pinyin: 'xiǎojiě',
    answer: 'Miss',
    wrongAnswers: ['Mr', 'teacher', 'student'],
    topic: 'People and Things',
    lesson: '3',
  },
  {
    character: '老师',
    pinyin: 'lǎoshī',
    answer: 'teacher',
    wrongAnswers: ['friend', 'cat', 'book'],
    topic: 'People and Things',
    lesson: '3',
  },
  {
    character: '学生',
    pinyin: 'xuésheng',
    answer: 'student',
    wrongAnswers: ['teacher', 'dog', 'apple'],
    topic: 'People and Things',
    lesson: '3',
  },
  {
    character: '同学',
    pinyin: 'tóngxué',
    answer: 'schoolmate',
    wrongAnswers: ['friend', 'teacher', 'book'],
    topic: 'People and Things',
    lesson: '3',
  },
  {
    character: '医生',
    pinyin: 'yīshēng',
    answer: 'doctor',
    wrongAnswers: ['teacher', 'fruit', 'water'],
    topic: 'People and Things',
    lesson: '0',
  },
  {
    character: '东西',
    pinyin: 'dōngxi',
    answer: 'thing',
    wrongAnswers: ['book', 'apple', 'dog'],
    topic: 'People and Things',
    lesson: '0',
  },
  {
    character: '钱',
    pinyin: 'qián',
    answer: 'money',
    wrongAnswers: ['cup', 'year', 'friend'],
    topic: 'People and Things',
    lesson: '8',
  },
  {
    character: '水',
    pinyin: 'shuǐ',
    answer: 'water',
    wrongAnswers: ['dog', 'book', 'teacher'],
    topic: 'People and Things',
    lesson: '0',
  },
  {
    character: '茶',
    pinyin: 'chá',
    answer: 'tea',
    wrongAnswers: ['apple', 'money', 'book'],
    topic: 'People and Things',
    lesson: '8',
  },
  {
    character: '菜',
    pinyin: 'cài',
    answer: 'dish',
    wrongAnswers: ['dog', 'year', 'friend'],
    topic: 'People and Things',
    lesson: '6',
  },
  {
    character: '米饭',
    pinyin: 'mǐfàn',
    answer: '(cooked) rice',
    wrongAnswers: ['cat', 'apple', 'dog'],
    topic: 'People and Things',
    lesson: '8',
  },
  {
    character: '衣服',
    pinyin: 'yīfu',
    answer: 'clothes',
    wrongAnswers: ['book', 'cup', 'water'],
    topic: 'People and Things',
    lesson: '6',
  },
  {
    character: '书',
    pinyin: 'shū',
    answer: 'book',
    wrongAnswers: ['money', 'apple', 'cat'],
    topic: 'People and Things',
    lesson: '6',
  },
  {
    character: '桌子',
    pinyin: 'zhuōzi',
    answer: 'table or desk',
    wrongAnswers: ['chair', 'dog', 'book'],
    topic: 'People and Things',
    lesson: '6',
  },
  {
    character: '椅子',
    pinyin: 'yǐzi',
    answer: 'chair',
    wrongAnswers: ['table', 'desk', 'bed'],
    topic: 'People and Things',
    lesson: '6',
  },
  {
    character: '水果',
    pinyin: 'shuǐguǒ',
    answer: 'fruit',
    wrongAnswers: ['vegetable', 'meat', 'bread'],
    topic: 'People and Things',
    lesson: '6',
  },
  {
    character: '苹果',
    pinyin: 'píngguǒ',
    answer: 'apple',
    wrongAnswers: ['banana', 'orange', 'grape'],
    topic: 'People and Things',
    lesson: '6',
  },
  {
    character: '杯子',
    pinyin: 'bēizi',
    answer: 'cup or glass',
    wrongAnswers: ['plate', 'bowl', 'fork'],
    topic: 'People and Things',
    lesson: '8',
  },
  {
    character: '电视',
    pinyin: 'diànshì',
    answer: 'TV',
    wrongAnswers: ['radio', 'computer', 'phone'],
    topic: 'People and Things',
    lesson: '6',
  },
  {
    character: '电脑',
    pinyin: 'diànnǎo',
    answer: 'computer',
    wrongAnswers: ['printer', 'scanner', 'keyboard'],
    topic: 'People and Things',
    lesson: '6',
  },
  {
    character: '电影',
    pinyin: 'diànyǐng',
    answer: 'movie',
    wrongAnswers: ['book', 'music', 'painting'],
    topic: 'People and Things',
    lesson: '6',
  },
  {
    character: '飞机',
    pinyin: 'fēijī',
    answer: 'plane',
    wrongAnswers: ['car', 'boat', 'train'],
    topic: 'People and Things',
    lesson: '6',
  },
  {
    character: '出租车',
    pinyin: 'chūzūchē',
    answer: 'taxi',
    wrongAnswers: ['bus', 'bike', 'subway'],
    topic: 'People and Things',
    lesson: '6',
  },
  {
    character: '猫',
    pinyin: 'māo',
    answer: 'cat',
    wrongAnswers: ['dog', 'bird', 'fish'],
    topic: 'People and Things',
    lesson: '6',
  },
  {
    character: '狗',
    pinyin: 'gǒu',
    answer: 'dog',
    wrongAnswers: ['cat', 'horse', 'rabbit'],
    topic: 'People and Things',
    lesson: '6',
  },
  {
    character: '天气',
    pinyin: 'tiānqì',
    answer: 'weather',
    wrongAnswers: ['time', 'season', 'temperature'],
    topic: 'People and Things',
    lesson: '6',
  },
  {
    character: '字',
    pinyin: 'zì',
    answer: 'character',
    wrongAnswers: ['word', 'letter', 'symbol'],
    topic: 'People and Things',
    lesson: '6',
  },
  {
    character: '汉语',
    pinyin: 'Hànyǔ',
    answer: 'Chinese (language)',
    wrongAnswers: ['English', 'Spanish', 'French'],
    topic: 'People and Things',
    lesson: '6',
  },
  {
    character: '中国',
    pinyin: 'Zhōngguó',
    answer: 'China',
    wrongAnswers: ['Japan', 'Korea', 'India'],
    topic: 'Places and Directions',
    lesson: '3',
  },
  {
    character: '北京',
    pinyin: 'Běijīng',
    answer: 'Beijing',
    wrongAnswers: ['Shanghai', 'Guangzhou', 'Hong Kong'],
    topic: 'Places and Directions',
    lesson: '3',
  },
  {
    character: '家',
    pinyin: 'jiā',
    answer: 'home or family',
    wrongAnswers: ['school', 'restaurant', 'hospital'],
    topic: 'Places and Directions',
    lesson: '5',
  },
  {
    character: '学校',
    pinyin: 'xuéxiào',
    answer: 'school',
    wrongAnswers: ['shop', 'restaurant', 'hospital'],
    topic: 'Places and Directions',
    lesson: '7',
  },
  {
    character: '饭馆',
    pinyin: 'fànguǎn',
    answer: 'restaurant',
    wrongAnswers: ['shop', 'school', 'hospital'],
    topic: 'Places and Directions',
    lesson: '7',
  },
  {
    character: '商店',
    pinyin: 'shāngdiàn',
    answer: 'shop',
    wrongAnswers: ['restaurant', 'school', 'hospital'],
    topic: 'Places and Directions',
    lesson: '7',
  },
  {
    character: '医院',
    pinyin: 'yīyuàn',
    answer: 'hospital',
    wrongAnswers: ['shop', 'school', 'restaurant'],
    topic: 'Places and Directions',
    lesson: '7',
  },
  {
    character: '火车站',
    pinyin: 'huǒchēzhàn',
    answer: 'train station',
    wrongAnswers: ['airport', 'bus stop', 'subway station'],
    topic: 'Places and Directions',
    lesson: '7',
  },
  {
    character: '上',
    pinyin: 'shàng',
    answer: 'on, above or last',
    wrongAnswers: ['under, below', 'next', 'inside'],
    topic: 'Places and Directions',
    lesson: '7',
  },
  {
    character: '下',
    pinyin: 'xià',
    answer: 'under, below or next',
    wrongAnswers: ['on, above', 'last', 'inside'],
    topic: 'Places and Directions',
    lesson: '7',
  },
  {
    character: '前面',
    pinyin: 'qiánmiàn',
    answer: 'front',
    wrongAnswers: ['back', 'inside', 'side'],
    topic: 'Places and Directions',
    lesson: '7',
  },
  {
    character: '后面',
    pinyin: 'hòumiàn',
    answer: 'back',
    wrongAnswers: ['front', 'inside', 'side'],
    topic: 'Places and Directions',
    lesson: '7',
  },
  {
    character: '里',
    pinyin: 'lǐ',
    answer: 'inside',
    wrongAnswers: ['outside', 'near', 'far'],
    topic: 'Places and Directions',
    lesson: '7',
  },

  {
    character: '个',
    pinyin: 'gè',
    answer: 'generic measure word',
    wrongAnswers: ['big', 'small', 'round'],
    topic: 'Measure Words',
    lesson: '8',
  },
  {
    character: '块',
    pinyin: 'kuài',
    answer: 'basic monetary unit of China',
    wrongAnswers: ['coin', 'note', 'dollar'],
    topic: 'Measure Words',
    lesson: '8',
  },
  {
    character: '本',
    pinyin: 'běn',
    answer: 'for books',
    wrongAnswers: ['for food', 'for clothes', 'for electronics'],
    topic: 'Measure Words',
    lesson: '7',
  },
  {
    character: '岁',
    pinyin: 'suì',
    answer: 'year (of age)',
    wrongAnswers: ['month', 'day', 'hour'],
    topic: 'Measure Words',
    lesson: '5',
  },
  {
    character: '些',
    pinyin: 'xiē',
    answer: 'some',
    wrongAnswers: ['many', 'few', 'all'],
    topic: 'Measure Words',
    lesson: '5',
  },
  {
    character: '做',
    pinyin: 'zuò',
    answer: 'to do',
    wrongAnswers: ['to eat', 'to go', 'to come'],
    topic: 'Verbs',
    lesson: '6',
  },
  {
    character: '是',
    pinyin: 'shì',
    answer: 'to be',
    wrongAnswers: ['to do', 'to have', 'to go'],
    topic: 'Verbs',
    lesson: '6',
  },
  {
    character: '在',
    pinyin: 'zài',
    answer: 'to be in',
    wrongAnswers: ['to do', 'to have', 'to go'],
    topic: 'Verbs',
    lesson: '6',
  },
  {
    character: '有',
    pinyin: 'yǒu',
    answer: 'to have',
    wrongAnswers: ['to be', 'to do', 'to go'],
    topic: 'Verbs',
    lesson: '6',
  },
  {
    character: '住',
    pinyin: 'zhù',
    answer: 'to live or to stay',
    wrongAnswers: ['to eat', 'to go', 'to come'],
    topic: 'Verbs',
    lesson: '6',
  },
  {
    character: '来',
    pinyin: 'lái',
    answer: 'to come',
    wrongAnswers: ['to go', 'to do', 'to have'],
    topic: 'Verbs',
    lesson: '6',
  },
  {
    character: '去',
    pinyin: 'qù',
    answer: 'to go',
    wrongAnswers: ['to come', 'to do', 'to be'],
    topic: 'Verbs',
    lesson: '7',
  },
  {
    character: '回',
    pinyin: 'huí',
    answer: 'to return',
    wrongAnswers: ['to go', 'to come', 'to do'],
    topic: 'Verbs',
    lesson: '6',
  },
  {
    character: '想',
    pinyin: 'xiǎng',
    answer: 'to want, would like',
    wrongAnswers: ['to eat', 'to go', 'to come'],
    topic: 'Verbs',
    lesson: '8',
  },
  {
    character: '吃',
    pinyin: 'chī',
    answer: 'to eat',
    wrongAnswers: ['to do', 'to go', 'to come'],
    topic: 'Verbs',
    lesson: '8',
  },
  {
    character: '喝',
    pinyin: 'hē',
    answer: 'to drink',
    wrongAnswers: ['to eat', 'to sleep', 'to talk'],
    topic: 'Verbs',
    lesson: '8',
  },
  {
    character: '说话',
    pinyin: 'shuōhuà',
    answer: 'to speak',
    wrongAnswers: ['to read', 'to listen', 'to buy'],
    topic: 'Verbs',
    lesson: '6',
  },
  {
    character: '看',
    pinyin: 'kàn',
    answer: 'to look or to watch',
    wrongAnswers: ['to eat', 'to drive', 'to read'],
    topic: 'Verbs',
    lesson: '7',
  },
  {
    character: '看见',
    pinyin: 'kànjiàn',
    answer: 'to see',
    wrongAnswers: ['to read', 'to listen', 'to buy'],
    topic: 'Verbs',
    lesson: '7',
  },
  {
    character: '听',
    pinyin: 'tīng',
    answer: 'to listen',
    wrongAnswers: ['to speak', 'to drive', 'to buy'],
    topic: 'Verbs',
    lesson: '7',
  },
  {
    character: '叫',
    pinyin: 'jiào',
    answer: 'to call',
    wrongAnswers: ['to sit', 'to open', 'to drink'],
    topic: 'Verbs',
    lesson: '3',
  },
  {
    character: '买',
    pinyin: 'mǎi',
    answer: 'to buy',
    wrongAnswers: ['to drive', 'to sit', 'to open'],
    topic: 'Verbs',
    lesson: '8',
  },
  {
    character: '开',
    pinyin: 'kāi',
    answer: 'to drive or to open',
    wrongAnswers: ['to buy', 'to sit', 'to drink'],
    topic: 'Verbs',
    lesson: '7',
  },
  {
    character: '坐',
    pinyin: 'zuò',
    answer: 'to sit',
    wrongAnswers: ['to drink', 'to drive', 'to read'],
    topic: 'Verbs',
    lesson: '7',
  },
  {
    character: '读',
    pinyin: 'dú',
    answer: 'to read',
    wrongAnswers: ['to listen', 'to watch', 'to buy'],
    topic: 'Verbs',
    lesson: '6',
  },
  {
    character: '写',
    pinyin: 'xiě',
    answer: 'to write',
    wrongAnswers: ['to read', 'to learn', 'to work'],
    topic: 'Verbs',
    lesson: '6',
  },
  {
    character: '打电话',
    pinyin: 'dǎ diànhuà',
    answer: 'to make a phone call',
    wrongAnswers: ['to write', 'to learn', 'to work'],
    topic: 'Verbs',
    lesson: '6',
  },
  {
    character: '认识',
    pinyin: 'rènshi',
    answer: 'to know',
    wrongAnswers: ['to learn', 'to work', 'to write'],
    topic: 'Verbs',
    lesson: '6',
  },
  {
    character: '学习',
    pinyin: 'xuéxí',
    answer: 'to learn',
    wrongAnswers: ['to write', 'to know', 'to work'],
    topic: 'Verbs',
    lesson: '6',
  },
  {
    character: '工作',
    pinyin: 'gōngzuò',
    answer: 'to work',
    wrongAnswers: ['to learn', 'to know', 'to write'],
    topic: 'Verbs',
    lesson: '6',
  },
  {
    character: '睡觉',
    pinyin: 'shuìjiào',
    answer: 'to sleep',
    wrongAnswers: ['to work', 'to learn', 'to write'],
    topic: 'Verbs',
    lesson: '6',
  },
  {
    character: '喜欢',
    pinyin: 'xǐhuan',
    answer: 'to like',
    wrongAnswers: ['to love', 'to know', 'to work'],
    topic: 'Verbs',
    lesson: '7',
  },
  {
    character: '爱',
    pinyin: 'ài',
    answer: 'to love',
    wrongAnswers: ['to like', 'to know', 'to work'],
    topic: 'Verbs',
    lesson: '7',
  },
  {
    character: '会',
    pinyin: 'huì',
    answer: 'can (to know how to)',
    wrongAnswers: ['to be able to', 'to learn', 'to work'],
    topic: 'Verbs',
    lesson: '6',
  },
  {
    character: '能',
    pinyin: 'néng',
    answer: 'can (to be able to)',
    wrongAnswers: ['to know', 'to learn', 'to work'],
    topic: 'Verbs',
    lesson: '6',
  },
  {
    character: '下雨',
    pinyin: 'xià yǔ',
    answer: 'to rain',
    wrongAnswers: ['to snow', 'to shine', 'to be windy'],
    topic: 'Verbs',
    lesson: '6',
  },
  {
    character: '好',
    pinyin: 'hǎo',
    answer: 'good',
    wrongAnswers: ['bad', 'big', 'small'],
    topic: 'Adjectives and Adverbs',
    lesson: '6',
  },
  {
    character: '大',
    pinyin: 'dà',
    answer: 'big',
    wrongAnswers: ['small', 'good', 'bad'],
    topic: 'Adjectives and Adverbs',
    lesson: '5',
  },
  {
    character: '小',
    pinyin: 'xiǎo',
    answer: 'small',
    wrongAnswers: ['big', 'good', 'bad'],
    topic: 'Adjectives and Adverbs',
    lesson: '5',
  },
  {
    character: '多',
    pinyin: 'duō',
    answer: 'many',
    wrongAnswers: ['few', 'big', 'small'],
    topic: 'Adjectives and Adverbs',
    lesson: '5',
  },
  {
    character: '少',
    pinyin: 'shǎo',
    answer: 'few',
    wrongAnswers: ['many', 'big', 'small'],
    topic: 'Adjectives and Adverbs',
    lesson: '0',
  },
  {
    character: '热',
    pinyin: 'rè',
    answer: 'hot',
    wrongAnswers: ['cold', 'good', 'bad'],
    topic: 'Adjectives and Adverbs',
    lesson: '0',
  },
  {
    character: '冷',
    pinyin: 'lěng',
    answer: 'cold',
    wrongAnswers: ['hot', 'good', 'bad'],
    topic: 'Adjectives and Adverbs',
    lesson: '0',
  },
  {
    character: '漂亮',
    pinyin: 'piàoliang',
    answer: 'pretty',
    wrongAnswers: ['ugly', 'beautiful', 'good'],
    topic: 'Adjectives and Adverbs',
    lesson: '0',
  },
  {
    character: '高兴',
    pinyin: 'gāoxìng',
    answer: 'happy',
    wrongAnswers: ['sad', 'excited', 'good'],
    topic: 'Adjectives and Adverbs',
    lesson: '0',
  },
  {
    character: '很',
    pinyin: 'hěn',
    answer: 'very',
    wrongAnswers: ['too', 'a lot', 'little'],
    topic: 'Adjectives and Adverbs',
    lesson: '6',
  },
  {
    character: '太',
    pinyin: 'tài',
    answer: 'too…',
    wrongAnswers: ['very', 'a lot', 'little'],
    topic: 'Adjectives and Adverbs',
    lesson: '0',
  },
  {
    character: '都',
    pinyin: 'dōu',
    answer: 'both or all',
    wrongAnswers: ['neither', 'only', 'some'],
    topic: 'Adjectives and Adverbs',
    lesson: '0',
  },
  {
    character: '不',
    pinyin: 'bù',
    answer: 'not',
    wrongAnswers: ['yes', 'no', 'maybe'],
    topic: 'Adjectives and Adverbs',
    lesson: '2',
  },
  {
    character: '没',
    pinyin: 'méi',
    answer: 'not',
    wrongAnswers: ['yes', 'no', 'maybe'],
    topic: 'Adjectives and Adverbs',
    lesson: '2',
  },
  {
    character: '喂',
    pinyin: 'wèi',
    answer: 'hello (on the phone)',
    wrongAnswers: ['thanks', 'goodbye', 'please'],
    topic: 'Expressions',
    lesson: '2',
  },
  {
    character: '谢谢',
    pinyin: 'xièxie',
    answer: 'thanks',
    wrongAnswers: ['hello', 'you’re welcome', 'please'],
    topic: 'Expressions',
    lesson: '2',
  },
  {
    character: '不客气',
    pinyin: 'bú kèqi',
    answer: 'you’re welcome',
    wrongAnswers: ['thanks', 'it’s all right', 'please'],
    topic: 'Expressions',
    lesson: '2',
  },
  {
    character: '再见',
    pinyin: 'zàijiàn',
    answer: 'goodbye',
    wrongAnswers: ['hello', 'thanks', 'please'],
    topic: 'Expressions',
    lesson: '2',
  },
  {
    character: '请',
    pinyin: 'qǐng',
    answer: 'please…',
    wrongAnswers: ['hello', 'thanks', 'goodbye'],
    topic: 'Expressions',
    lesson: '7',
  },
  {
    character: '对不起',
    pinyin: 'duìbuqǐ',
    answer: 'sorry',
    wrongAnswers: ['hello', 'thanks', 'goodbye'],
    topic: 'Expressions',
    lesson: '1',
  },
  {
    character: '没关系',
    pinyin: 'méi guānxi',
    answer: 'it’s all right',
    wrongAnswers: ['you’re welcome', 'thanks', 'sorry'],
    topic: 'Expressions',
    lesson: '1',
  },
  {
    character: '号',
    pinyin: 'hào',
    answer: 'number',
    wrongAnswers: ['book', 'ask', 'date'],
    topic: 'Date and Time',
    lesson: '7',
  },
  {
    character: '书',
    pinyin: 'shū',
    answer: 'book',
    wrongAnswers: ['number', 'ask', 'date'],
    topic: 'Reading',
    lesson: '7',
  },
  {
    character: '问',
    pinyin: 'wèn',
    answer: 'to ask',
    wrongAnswers: ['number', 'book', 'date'],
    topic: 'Communication',
    lesson: '7',
  },
  {
    character: '想',
    pinyin: 'xiǎng',
    answer: 'to want, would like',
    wrongAnswers: ['to eat', 'afternoon', 'money'],
    topic: 'Daily Activities',
    lesson: '8',
  },
  {
    character: '喝',
    pinyin: 'hē',
    answer: 'to drink',
    wrongAnswers: ['shop', 'cup', 'rice'],
    topic: 'Daily Activities',
    lesson: '8',
  },
  {
    character: '茶',
    pinyin: 'chá',
    answer: 'tea',
    wrongAnswers: ['this', 'that', 'book'],
    topic: 'Daily Activities',
    lesson: '8',
  },
  {
    character: '吃',
    pinyin: 'chī',
    answer: 'to eat',
    wrongAnswers: ['money', 'cup', 'afternoon'],
    topic: 'Daily Activities',
    lesson: '8',
  },
  {
    character: '米饭',
    pinyin: 'mǐfàn',
    answer: 'rice',
    wrongAnswers: ['book', 'to want', 'shop'],
    topic: 'Daily Activities',
    lesson: '8',
  },
  {
    character: '下午',
    pinyin: 'xiàwǔ',
    answer: 'afternoon',
    wrongAnswers: ['to drink', 'money', 'cup'],
    topic: 'Daily Activities',
    lesson: '8',
  },
  {
    character: '商店',
    pinyin: 'shāngdiàn',
    answer: 'shop, store',
    wrongAnswers: ['this', 'rice', 'book'],
    topic: 'Daily Activities',
    lesson: '8',
  },
  {
    character: '买',
    pinyin: 'mǎi',
    answer: 'to buy, to purchase',
    wrongAnswers: ['to eat', 'afternoon', 'cup'],
    topic: 'Daily Activities',
    lesson: '8',
  },
  {
    character: '个',
    pinyin: 'gè',
    answer: 'a general measure word',
    wrongAnswers: ['tea', 'book', 'shop'],
    topic: 'Daily Activities',
    lesson: '8',
  },
  {
    character: '杯子',
    pinyin: 'bēizi',
    answer: 'cup, glass',
    wrongAnswers: ['to want', 'to eat', 'money'],
    topic: 'Daily Activities',
    lesson: '8',
  },
  {
    character: '这',
    pinyin: 'zhè',
    answer: 'this',
    wrongAnswers: ['rice', 'afternoon', 'tea'],
    topic: 'Daily Activities',
    lesson: '8',
  },
  {
    character: '多少',
    pinyin: 'duōshao',
    answer: 'how many, how much (to ask numbers larger than 10)',
    wrongAnswers: ['book', 'shop', 'cup'],
    topic: 'Daily Activities',
    lesson: '8',
  },
  {
    character: '钱',
    pinyin: 'qián',
    answer: 'money',
    wrongAnswers: ['afternoon', 'to drink', 'rice'],
    topic: 'Daily Activities',
    lesson: '8',
  },
  {
    character: '块',
    pinyin: 'kuài',
    answer: "a unit of money, same as 'yuan'",
    wrongAnswers: ['book', 'tea', 'this'],
    topic: 'Daily Activities',
    lesson: '8',
  },
  {
    character: '那',
    pinyin: 'nà',
    answer: 'that',
    wrongAnswers: ['rice', 'to eat', 'afternoon'],
    topic: 'Daily Activities',
    lesson: '8',
  },
  {
    character: '小',
    pinyin: 'xiǎo',
    answer: 'small, little',
    wrongAnswers: ['big', 'old', 'tall'],
    topic: 'Everyday Objects',
    lesson: '9',
  },
  {
    character: '猫',
    pinyin: 'māo',
    answer: 'cat',
    wrongAnswers: ['dog', 'bird', 'fish'],
    topic: 'Everyday Objects',
    lesson: '9',
  },
  {
    character: '在',
    pinyin: 'zài',
    answer: 'in, on, at',
    wrongAnswers: ['under', 'above', 'between'],
    topic: 'Everyday Objects',
    lesson: '9',
  },
  {
    character: '那儿',
    pinyin: 'nàr',
    answer: 'there',
    wrongAnswers: ['here', 'everywhere', 'nowhere'],
    topic: 'Everyday Objects',
    lesson: '9',
  },
  {
    character: '狗',
    pinyin: 'gǒu',
    answer: 'dog',
    wrongAnswers: ['cat', 'bird', 'fish'],
    topic: 'Everyday Objects',
    lesson: '9',
  },
  {
    character: '椅子',
    pinyin: 'yǐzi',
    answer: 'chair',
    wrongAnswers: ['table', 'bed', 'sofa'],
    topic: 'Everyday Objects',
    lesson: '9',
  },
  {
    character: '下',
    pinyin: 'xià',
    answer: 'under, below',
    wrongAnswers: ['above', 'on', 'between'],
    topic: 'Everyday Objects',
    lesson: '9',
  },
  {
    character: '哪儿',
    pinyin: 'nǎr',
    answer: 'where',
    wrongAnswers: ['here', 'there', 'everywhere'],
    topic: 'Everyday Objects',
    lesson: '9',
  },
  {
    character: '工作',
    pinyin: 'gōngzuò',
    answer: 'job, work',
    wrongAnswers: ['school', 'home', 'play'],
    topic: 'Everyday Objects',
    lesson: '9',
  },
  {
    character: '儿子',
    pinyin: 'érzi',
    answer: 'son',
    wrongAnswers: ['daughter', 'father', 'mother'],
    topic: 'Everyday Objects',
    lesson: '9',
  },
  {
    character: '医院',
    pinyin: 'yīyuàn',
    answer: 'hospital',
    wrongAnswers: ['school', 'home', 'office'],
    topic: 'Everyday Objects',
    lesson: '9',
  },
  {
    character: '医生',
    pinyin: 'yīshēng',
    answer: 'doctor',
    wrongAnswers: ['teacher', 'engineer', 'nurse'],
    topic: 'Everyday Objects',
    lesson: '9',
  },
  {
    character: '爸爸',
    pinyin: 'bàba',
    answer: 'father',
    wrongAnswers: ['mother', 'son', 'daughter'],
    topic: 'Everyday Objects',
    lesson: '9',
  },
  {
    character: '桌子',
    pinyin: 'zhuōzi',
    answer: 'table, desk',
    wrongAnswers: ['chair', 'bed', 'book'],
    topic: 'Everyday Spaces',
    lesson: '10',
  },
  {
    character: '上',
    pinyin: 'shàng',
    answer: 'up, above',
    wrongAnswers: ['down', 'below', 'under'],
    topic: 'Everyday Spaces',
    lesson: '10',
  },
  {
    character: '电脑',
    pinyin: 'diànnǎo',
    answer: 'computer',
    wrongAnswers: ['TV', 'phone', 'book'],
    topic: 'Everyday Spaces',
    lesson: '10',
  },
  {
    character: '和',
    pinyin: 'hé',
    answer: 'and',
    wrongAnswers: ['or', 'but', 'with'],
    topic: 'Everyday Spaces',
    lesson: '10',
  },
  {
    character: '本',
    pinyin: 'běn',
    answer: 'a measure word for books, dictionaries, magazines, etc.',
    wrongAnswers: ['table', 'computer', 'chair'],
    topic: 'Everyday Spaces',
    lesson: '10',
  },
  {
    character: '里',
    pinyin: 'lǐ',
    answer: 'inner, inside, interior',
    wrongAnswers: ['outside', 'front', 'back'],
    topic: 'Everyday Spaces',
    lesson: '10',
  },
  {
    character: '前面',
    pinyin: 'qiánmiàn',
    answer: 'front',
    wrongAnswers: ['back', 'inside', 'up'],
    topic: 'Everyday Spaces',
    lesson: '10',
  },
  {
    character: '后面',
    pinyin: 'hòumiàn',
    answer: 'back, behind',
    wrongAnswers: ['front', 'inside', 'up'],
    topic: 'Everyday Spaces',
    lesson: '10',
  },
  {
    character: '这儿',
    pinyin: 'zhèr',
    answer: 'here',
    wrongAnswers: ['there', 'everywhere', 'nowhere'],
    topic: 'Everyday Spaces',
    lesson: '10',
  },
  {
    character: '没（有）',
    pinyin: 'méi (yǒu)',
    answer: 'no, there is not',
    wrongAnswers: ['yes', 'maybe', 'always'],
    topic: 'Everyday Spaces',
    lesson: '10',
  },
  {
    character: '能',
    pinyin: 'néng',
    answer: 'can, may',
    wrongAnswers: ['should', 'will', 'must'],
    topic: 'Everyday Spaces',
    lesson: '10',
  },
  {
    character: '坐',
    pinyin: 'zuò',
    answer: 'to sit, to be seated',
    wrongAnswers: ['stand', 'walk', 'run'],
    topic: 'Everyday Spaces',
    lesson: '10',
  },
  {
    character: '现在',
    pinyin: 'xiànzài',
    answer: 'now',
    wrongAnswers: ['later', 'yesterday', 'tomorrow'],
    topic: 'Date and Time',
    lesson: '11',
  },
  {
    character: '点',
    pinyin: 'diǎn',
    answer: 'o’clock',
    wrongAnswers: ['minute', 'hour', 'day'],
    topic: 'Date and Time',
    lesson: '11',
  },
  {
    character: '分钟',
    pinyin: 'fēnzhōng',
    answer: 'minute',
    wrongAnswers: ['hour', 'day', 'week'],
    topic: 'Date and Time',
    lesson: '11',
  },
  {
    character: '上午',
    pinyin: 'shàngwǔ',
    answer: 'morning, before noon',
    wrongAnswers: ['afternoon', 'evening', 'night'],
    topic: 'Date and Time',
    lesson: '11',
  },
  {
    character: '中午',
    pinyin: 'zhōngwǔ',
    answer: 'noon',
    wrongAnswers: ['morning', 'afternoon', 'night'],
    topic: 'Date and Time',
    lesson: '11',
  },
  {
    character: '下午',
    pinyin: 'xiàwǔ',
    answer: 'afternoon',
    wrongAnswers: ['morning', 'evening', 'night'],
    topic: 'Date and Time',
    lesson: '11',
  },
  {
    character: '吃',
    pinyin: 'chī',
    answer: 'to eat',
    wrongAnswers: ['to drink', 'to sleep', 'to walk'],
    topic: 'Daily Activities',
    lesson: '11',
  },
  {
    character: '时候',
    pinyin: 'shíhou',
    answer: 'time, moment',
    wrongAnswers: ['place', 'person', 'thing'],
    topic: 'Date and Time',
    lesson: '11',
  },
  {
    character: '回',
    pinyin: 'huí',
    answer: 'to be back, to return',
    wrongAnswers: ['to go', 'to stay', 'to leave'],
    topic: 'Daily Activities',
    lesson: '11',
  },
  {
    character: '我们',
    pinyin: 'wǒmen',
    answer: 'we, us',
    wrongAnswers: ['you', 'they', 'he'],
    topic: 'Pronouns',
    lesson: '11',
  },
  {
    character: '电影',
    pinyin: 'diànyǐng',
    answer: 'movie',
    wrongAnswers: ['book', 'music', 'painting'],
    topic: 'Daily Activities',
    lesson: '11',
  },
  {
    character: '住',
    pinyin: 'zhù',
    answer: 'to live, to stay',
    wrongAnswers: ['to go', 'to come', 'to leave'],
    topic: 'Daily Activities',
    lesson: '11',
  },
  {
    character: '前',
    pinyin: 'qián',
    answer: 'before, earlier than',
    wrongAnswers: ['after', 'during', 'later than'],
    topic: 'Date and Time',
    lesson: '11',
  },
  {
    character: '天气',
    pinyin: 'tiānqì',
    answer: 'weather',
    wrongAnswers: ['time', 'season', 'temperature'],
    topic: 'Weather and Expressions',
    lesson: '12',
  },
  {
    character: '怎么样',
    pinyin: 'zěnmeyàng',
    answer: 'how (is it)',
    wrongAnswers: ['what', 'when', 'why'],
    topic: 'Weather and Expressions',
    lesson: '12',
  },
  {
    character: '太',
    pinyin: 'tài',
    answer: 'too, excessively',
    wrongAnswers: ['very', 'not', 'also'],
    topic: 'Weather and Expressions',
    lesson: '12',
  },
  {
    character: '热',
    pinyin: 'rè',
    answer: 'hot',
    wrongAnswers: ['cold', 'warm', 'cool'],
    topic: 'Weather and Expressions',
    lesson: '12',
  },
  {
    character: '冷',
    pinyin: 'lěng',
    answer: 'cold',
    wrongAnswers: ['hot', 'warm', 'cool'],
    topic: 'Weather and Expressions',
    lesson: '12',
  },
  {
    character: '下雨',
    pinyin: 'xiàyǔ',
    answer: 'to rain',
    wrongAnswers: ['to snow', 'to shine', 'to hail'],
    topic: 'Weather and Expressions',
    lesson: '12',
  },
  {
    character: '下',
    pinyin: 'xià',
    answer: '(of rain, snow, etc) to fall',
    wrongAnswers: ['up', 'down', 'to go'],
    topic: 'Weather and Expressions',
    lesson: '12',
  },
  {
    character: '雨',
    pinyin: 'yǔ',
    answer: 'rain',
    wrongAnswers: ['snow', 'wind', 'cloud'],
    topic: 'Weather and Expressions',
    lesson: '12',
  },
  {
    character: '小姐',
    pinyin: 'xiǎojiě',
    answer: 'miss, young lady',
    wrongAnswers: ['Mr.', 'Mrs.', 'sir'],
    topic: 'Weather and Expressions',
    lesson: '12',
  },
  {
    character: '来',
    pinyin: 'lái',
    answer: 'to come',
    wrongAnswers: ['to go', 'to stay', 'to leave'],
    topic: 'Weather and Expressions',
    lesson: '12',
  },
  {
    character: '身体',
    pinyin: 'shēntǐ',
    answer: 'body',
    wrongAnswers: ['head', 'leg', 'arm'],
    topic: 'Weather and Expressions',
    lesson: '12',
  },
  {
    character: '爱',
    pinyin: 'ài',
    answer: 'to like, to love',
    wrongAnswers: ['to hate', 'to dislike', 'to ignore'],
    topic: 'Weather and Expressions',
    lesson: '12',
  },
  {
    character: '些',
    pinyin: 'xiē',
    answer: 'some, a few, a little',
    wrongAnswers: ['many', 'all', 'none'],
    topic: 'Weather and Expressions',
    lesson: '12',
  },
  {
    character: '水果',
    pinyin: 'shuǐguǒ',
    answer: 'fruit',
    wrongAnswers: ['vegetable', 'meat', 'bread'],
    topic: 'Weather and Expressions',
    lesson: '12',
  },
  {
    character: '水',
    pinyin: 'shuǐ',
    answer: 'water',
    wrongAnswers: ['fire', 'earth', 'wind'],
    topic: 'Weather and Expressions',
    lesson: '12',
  },
  {
    character: '书店',
    pinyin: 'shūdiàn',
    answer: 'bookstore',
    wrongAnswers: ['coffee shop', 'department store', 'pharmacy'],
    topic: 'Places and Directions',
    lesson: '8',
  },
  {
    character: '咖啡店',
    pinyin: 'kāfēidiàn',
    answer: 'coffee shop',
    wrongAnswers: ['bookstore', 'restaurant', 'supermarket'],
    topic: 'Places and Directions',
    lesson: '8',
  },
  {
    character: '花店',
    pinyin: 'huādiàn',
    answer: 'flower shop',
    wrongAnswers: ['bakery', 'pharmacy', 'library'],
    topic: 'Places and Directions',
    lesson: '8',
  },
  {
    character: '饭店',
    pinyin: 'fàndiàn',
    answer: 'restaurant',
    wrongAnswers: ['hotel', 'bank', 'post office'],
    topic: 'Places and Directions',
    lesson: '8',
  },
  {
    character: '医服店',
    pinyin: 'yīfúdiàn',
    answer: 'clothing store',
    wrongAnswers: ['bookstore', 'electronics store', 'grocery store'],
    topic: 'Places and Directions',
    lesson: '8',
  },
  {
    character: '药店',
    pinyin: 'yàodiàn',
    answer: 'pharmacy',
    wrongAnswers: ['hardware store', 'flower shop', 'movie theater'],
    topic: 'Places and Directions',
    lesson: '8',
  },
  {
    character: '左',
    pinyin: 'zuǒ',
    answer: 'left',
    wrongAnswers: ['right', 'up', 'down'],
    topic: 'Places and Directions',
    lesson: '9',
  },
  {
    character: '右',
    pinyin: 'yòu',
    answer: 'right',
    wrongAnswers: ['left', 'up', 'down'],
    topic: 'Places and Directions',
    lesson: '9',
  },
  {
    character: '前',
    pinyin: 'qián',
    answer: 'front',
    wrongAnswers: ['back', 'left', 'right'],
    topic: 'Places and Directions',
    lesson: '9',
  },
  {
    character: '后',
    pinyin: 'hòu',
    answer: 'back',
    wrongAnswers: ['front', 'left', 'right'],
    topic: 'Places and Directions',
    lesson: '9',
  },
  {
    character: '东',
    pinyin: 'dōng',
    answer: 'east',
    wrongAnswers: ['west', 'north', 'south'],
    topic: 'Places and Directions',
    lesson: '9',
  },
  {
    character: '西',
    pinyin: 'xī',
    answer: 'west',
    wrongAnswers: ['east', 'north', 'south'],
    topic: 'Places and Directions',
    lesson: '9',
  },
  {
    character: '南',
    pinyin: 'nán',
    answer: 'south',
    wrongAnswers: ['north', 'east', 'west'],
    topic: 'Places and Directions',
    lesson: '9',
  },
  {
    character: '北',
    pinyin: 'běi',
    answer: 'north',
    wrongAnswers: ['south', 'east', 'west'],
    topic: 'Places and Directions',
    lesson: '9',
  },
  {
    character: '中',
    pinyin: 'zhōng',
    answer: 'middle',
    wrongAnswers: ['left', 'right', 'front'],
    topic: 'Places and Directions',
    lesson: '9',
  },
  {
    character: '里',
    pinyin: 'lǐ',
    answer: 'inside',
    wrongAnswers: ['outside', 'front', 'back'],
    topic: 'Places and Directions',
    lesson: '9',
  },
  {
    character: '床户',
    pinyin: 'chuáng hù',
    answer: 'bedroom',
    wrongAnswers: ['living room', 'kitchen', 'bathroom'],
    topic: 'Places and Directions',
    lesson: '9',
  },
  {
    character: '床',
    pinyin: 'chuáng',
    answer: 'bed',
    wrongAnswers: ['chair', 'table', 'sofa'],
    topic: 'People and Things',
    lesson: '9',
  },
  {
    character: '桌子',
    pinyin: 'zhuōzi',
    answer: 'table',
    wrongAnswers: ['bed', 'chair', 'sofa'],
    topic: 'People and Things',
    lesson: '9',
  },
  {
    character: '椅子',
    pinyin: 'yǐzi',
    answer: 'chair',
    wrongAnswers: ['table', 'bed', 'sofa'],
    topic: 'People and Things',
    lesson: '9',
  },
  {
    character: '沙发',
    pinyin: 'shāfā',
    answer: 'sofa',
    wrongAnswers: ['table', 'bed', 'chair'],
    topic: 'People and Things',
    lesson: '9',
  },
  {
    character: '衣柜',
    pinyin: 'yīguì',
    answer: 'wardrobe',
    wrongAnswers: ['bookshelf', 'dresser', 'nightstand'],
    topic: 'People and Things',
    lesson: '9',
  },
  {
    character: '早上',
    pinyin: 'zǎoshang',
    answer: 'morning',
    wrongAnswers: ['afternoon', 'evening', 'night'],
    topic: 'Date and Time',
    lesson: '11',
  },
  {
    character: '晚上',
    pinyin: 'wǎnshang',
    answer: 'evening',
    wrongAnswers: ['morning', 'afternoon', 'night'],
    topic: 'Date and Time',
    lesson: '11',
  },
  {
    character: '起床',
    pinyin: 'qǐchuáng',
    answer: 'to get up',
    wrongAnswers: ['to go to bed', 'to sleep', 'to sit'],
    topic: 'Daily Activities',
    lesson: '11',
  },
  {
    character: '刷牙',
    pinyin: 'shuāyá',
    answer: 'to brush teeth',
    wrongAnswers: ['to wash face', 'to comb hair', 'to take a shower'],
    topic: 'Daily Activities',
    lesson: '11',
  },
  {
    character: '洗脸',
    pinyin: 'xǐliǎn',
    answer: 'to wash face',
    wrongAnswers: ['to brush teeth', 'to comb hair', 'to take a shower'],
    topic: 'Daily Activities',
    lesson: '11',
  },
  {
    character: '上课',
    pinyin: 'shàngkè',
    answer: 'to go to class',
    wrongAnswers: ['to go to work', 'to study', 'to exercise'],
    topic: 'Daily Activities',
    lesson: '11',
  },
  {
    character: '下课',
    pinyin: 'xiàkè',
    answer: 'to finish class',
    wrongAnswers: ['to start class', 'to go to work', 'to study'],
    topic: 'Daily Activities',
    lesson: '11',
  },
  {
    character: '上班',
    pinyin: 'shàngbān',
    answer: 'to go to work',
    wrongAnswers: ['to go to class', 'to study', 'to exercise'],
    topic: 'Daily Activities',
    lesson: '11',
  },
  {
    character: '下班',
    pinyin: 'xiàbān',
    answer: 'to finish work',
    wrongAnswers: ['to start work', 'to go to class', 'to study'],
    topic: 'Daily Activities',
    lesson: '11',
  },
  {
    character: '洗澡',
    pinyin: 'xǐzǎo',
    answer: 'to take a shower',
    wrongAnswers: ['to wash face', 'to brush teeth', 'to comb hair'],
    topic: 'Daily Activities',
    lesson: '11',
  },
  {
    character: '做作业',
    pinyin: 'zuò zuòyè',
    answer: 'to do homework',
    wrongAnswers: ['to read a book', 'to watch TV', 'to exercise'],
    topic: 'Daily Activities',
    lesson: '11',
  },
  {
    character: '睡觉',
    pinyin: 'shuìjiào',
    answer: 'to sleep',
    wrongAnswers: ['to eat', 'to study', 'to exercise'],
    topic: 'Daily Activities',
    lesson: '11',
  },
  {
    character: '天气',
    pinyin: 'tiānqì',
    answer: 'weather',
    wrongAnswers: ['time', 'season', 'temperature'],
    topic: 'Weather',
    lesson: '12',
  },
  {
    character: '晴天',
    pinyin: 'qíngtiān',
    answer: 'sunny day',
    wrongAnswers: ['rainy day', 'cloudy day', 'windy day'],
    topic: 'Weather',
    lesson: '12',
  },
  {
    character: '多云',
    pinyin: 'duōyún',
    answer: 'cloudy',
    wrongAnswers: ['sunny', 'rainy', 'windy'],
    topic: 'Weather',
    lesson: '12',
  },
  {
    character: '阴天',
    pinyin: 'yīntiān',
    answer: 'cloudy day',
    wrongAnswers: ['sunny day', 'rainy day', 'windy day'],
    topic: 'Weather',
    lesson: '12',
  },
  {
    character: '风',
    pinyin: 'fēng',
    answer: 'wind',
    wrongAnswers: ['rain', 'snow', 'cloud'],
    topic: 'Weather',
    lesson: '12',
  },
  {
    character: '雨',
    pinyin: 'yǔ',
    answer: 'rain',
    wrongAnswers: ['wind', 'snow', 'cloud'],
    topic: 'Weather',
    lesson: '12',
  },
  {
    character: '雪',
    pinyin: 'xuě',
    answer: 'snow',
    wrongAnswers: ['rain', 'wind', 'cloud'],
    topic: 'Weather',
    lesson: '12',
  },
  {
    character: '气温',
    pinyin: 'qìwēn',
    answer: 'temperature',
    wrongAnswers: ['humidity', 'pressure', 'wind speed'],
    topic: 'Weather',
    lesson: '12',
  },
  {
    character: '零上',
    pinyin: 'língshàng',
    answer: 'above zero',
    wrongAnswers: ['below zero', 'at zero', 'high temperature'],
    topic: 'Weather',
    lesson: '12',
  },
  {
    character: '零下',
    pinyin: 'língxià',
    answer: 'below zero',
    wrongAnswers: ['above zero', 'at zero', 'high temperature'],
    topic: 'Weather',
    lesson: '12',
  },
  {
    character: '度',
    pinyin: 'dù',
    answer: 'degree',
    wrongAnswers: ['hour', 'minute', 'second'],
    topic: 'Weather',
    lesson: '12',
  },
  {
    character: '刮风',
    pinyin: 'guāfēng',
    answer: 'windy',
    wrongAnswers: ['rainy', 'sunny', 'cloudy'],
    topic: 'Weather',
    lesson: '12',
  },
  {
    character: '寄结',
    pinyin: 'jìjié',
    answer: 'season',
    wrongAnswers: ['weather', 'temperature', 'humidity'],
    topic: 'Weather',
    lesson: '12',
  },
  {
    character: '春天',
    pinyin: 'chūntiān',
    answer: 'spring',
    wrongAnswers: ['summer', 'fall', 'winter'],
    topic: 'Weather',
    lesson: '12',
  },
  {
    character: '夏天',
    pinyin: 'xiàtiān',
    answer: 'summer',
    wrongAnswers: ['spring', 'fall', 'winter'],
    topic: 'Weather',
    lesson: '12',
  },
  {
    character: '秋天',
    pinyin: 'qiūtiān',
    answer: 'fall',
    wrongAnswers: ['spring', 'summer', 'winter'],
    topic: 'Weather',
    lesson: '12',
  },
  {
    character: '冬天',
    pinyin: 'dōngtiān',
    answer: 'winter',
    wrongAnswers: ['spring', 'summer', 'fall'],
    topic: 'Weather',
    lesson: '12',
  },
  {
    character: '雨伞',
    pinyin: 'yǔsǎn',
    answer: 'umbrella',
    wrongAnswers: ['sunscreen', 'hat', 'gloves'],
    topic: 'Weather',
    lesson: '12',
  },
  {
    character: '雨衣',
    pinyin: 'yǔyī',
    answer: 'raincoat',
    wrongAnswers: ['umbrella', 'sunglasses', 'scarf'],
    topic: 'Weather',
    lesson: '12',
  },
  {
    character: '高兴',
    pinyin: 'gāoxìng',
    answer: 'happy',
    wrongAnswers: ['sad', 'angry', 'tired'],
    topic: 'Health',
    lesson: '12',
  },
  {
    character: '难过',
    pinyin: 'nánguò',
    answer: 'sad',
    wrongAnswers: ['happy', 'angry', 'tired'],
    topic: 'Health',
    lesson: '12',
  },
  {
    character: '凉快',
    pinyin: 'liángkuai',
    answer: 'cool',
    wrongAnswers: ['hot', 'warm', 'cold'],
    topic: 'Health',
    lesson: '12',
  },
  {
    character: '感冒',
    pinyin: 'gǎnmào',
    answer: 'to have a cold',
    wrongAnswers: ['to have a fever', 'to be healthy', 'to feel warm'],
    topic: 'Health',
    lesson: '12',
  },
  {
    character: '头疼',
    pinyin: 'tóuténg',
    answer: 'headache',
    wrongAnswers: ['stomachache', 'backache', 'toothache'],
    topic: 'Health',
    lesson: '12',
  },
  {
    character: '发烧',
    pinyin: 'fāshāo',
    answer: 'to have a fever',
    wrongAnswers: ['to have a cold', 'to be healthy', 'to feel warm'],
    topic: 'Health',
    lesson: '12',
  },
  {
    character: '丧子疼',
    pinyin: 'sàngziténg',
    answer: 'sore throat',
    wrongAnswers: ['stomachache', 'headache', 'backache'],
    topic: 'Health',
    lesson: '12',
  },
  {
    character: '咳嗽',
    pinyin: 'késòu',
    answer: 'to cough',
    wrongAnswers: ['to sneeze', 'to hiccup', 'to laugh'],
    topic: 'Health',
    lesson: '12',
  },
  {
    character: '流鼻涕',
    pinyin: 'liúbítì',
    answer: 'to have a runny nose',
    wrongAnswers: ['to have a blocked nose', 'to have a headache', 'to have a sore throat'],
    topic: 'Health',
    lesson: '12',
  },
  {
    character: '打喷嚏',
    pinyin: 'dǎpēntì',
    answer: 'to sneeze',
    wrongAnswers: ['to cough', 'to hiccup', 'to laugh'],
    topic: 'Health',
    lesson: '12',
  },
  {
    character: '量体温',
    pinyin: 'liáng tǐwēn',
    answer: 'to measure body temperature',
    wrongAnswers: ['to measure blood pressure', 'to measure heart rate', 'to measure height'],
    topic: 'Health',
    lesson: '12',
  },
  {
    character: '吃药',
    pinyin: 'chī yào',
    answer: 'to take medicine',
    wrongAnswers: ['to eat food', 'to drink water', 'to exercise'],
    topic: 'Health',
    lesson: '12',
  },
  {
    character: '打针',
    pinyin: 'dǎzhēn',
    answer: 'to get an injection',
    wrongAnswers: ['to take medicine', 'to see a doctor', 'to rest'],
    topic: 'Health',
    lesson: '12',
  },
  {
    character: '暖和',
    pinyin: 'nuǎnhuo',
    answer: 'warm',
    wrongAnswers: ['hot', 'cool', 'cold'],
    topic: 'Health',
    lesson: '12',
  },
];
