export const quizData = [
  {
    character: 'あ',
    answer: 'a',
    wrongAnswers: ['i', 'e', 'u'],
    lesson: 'Basic Hiragana Vowels',
    topic: 'Alphabet',
  },
  {
    character: 'い',
    answer: 'i',
    wrongAnswers: ['a', 'e', 'o'],
    lesson: 'Basic Hiragana Vowels',
    topic: 'Alphabet',
  },
  {
    character: 'う',
    answer: 'u',
    wrongAnswers: ['o', 'a', 'i'],
    lesson: 'Basic Hiragana Vowels',
    topic: 'Alphabet',
  },
  {
    character: 'え',
    answer: 'e',
    wrongAnswers: ['o', 'u', 'i'],
    lesson: 'Basic Hiragana Vowels',
    topic: 'Alphabet',
  },
  {
    character: 'お',
    answer: 'o',
    wrongAnswers: ['u', 'e', 'a'],
    lesson: 'Basic Hiragana Vowels',
    topic: 'Alphabet',
  },
  {
    character: 'か',
    answer: 'ka',
    wrongAnswers: ['ki', 'ku', 'ke'],
    lesson: 'Basic Hiragana K Column',
    topic: 'Alphabet',
  },
  {
    character: 'き',
    answer: 'ki',
    wrongAnswers: ['ka', 'ku', 'ko'],
    lesson: 'Basic Hiragana K Column',
    topic: 'Alphabet',
  },
  {
    character: 'く',
    answer: 'ku',
    wrongAnswers: ['ka', 'ke', 'ko'],
    lesson: 'Basic Hiragana K Column',
    topic: 'Alphabet',
  },
  {
    character: 'け',
    answer: 'ke',
    wrongAnswers: ['ka', 'ki', 'ko'],
    lesson: 'Basic Hiragana K Column',
    topic: 'Alphabet',
  },
  {
    character: 'こ',
    answer: 'ko',
    wrongAnswers: ['ka', 'ki', 'ku'],
    lesson: 'Basic Hiragana K Column',
    topic: 'Alphabet',
  },
  {
    character: 'さ',
    answer: 'sa',
    wrongAnswers: ['shi', 'su', 'se'],
    lesson: 'Basic Hiragana S Column',
    topic: 'Alphabet',
  },
  {
    character: 'し',
    answer: 'shi',
    wrongAnswers: ['sa', 'su', 'so'],
    lesson: 'Basic Hiragana S Column',
    topic: 'Alphabet',
  },
  {
    character: 'す',
    answer: 'su',
    wrongAnswers: ['sa', 'shi', 'se'],
    lesson: 'Basic Hiragana S Column',
    topic: 'Alphabet',
  },
  {
    character: 'せ',
    answer: 'se',
    wrongAnswers: ['sa', 'shi', 'su'],
    lesson: 'Basic Hiragana S Column',
    topic: 'Alphabet',
  },
  {
    character: 'そ',
    answer: 'so',
    wrongAnswers: ['sa', 'shi', 'su'],
    lesson: 'Basic Hiragana S Column',
    topic: 'Alphabet',
  },
  {
    character: 'た',
    answer: 'ta',
    wrongAnswers: ['chi', 'tsu', 'te'],
    lesson: 'Basic Hiragana T Column',
    topic: 'Alphabet',
  },
  {
    character: 'ち',
    answer: 'chi',
    wrongAnswers: ['ta', 'tsu', 'to'],
    lesson: 'Basic Hiragana T Column',
    topic: 'Alphabet',
  },
  {
    character: 'つ',
    answer: 'tsu',
    wrongAnswers: ['ta', 'chi', 'te'],
    lesson: 'Basic Hiragana T Column',
    topic: 'Alphabet',
  },
  {
    character: 'て',
    answer: 'te',
    wrongAnswers: ['ta', 'chi', 'to'],
    lesson: 'Basic Hiragana T Column',
    topic: 'Alphabet',
  },
  {
    character: 'と',
    answer: 'to',
    wrongAnswers: ['ta', 'chi', 'tsu'],
    lesson: 'Basic Hiragana T Column',
    topic: 'Alphabet',
  },
  {
    character: 'な',
    answer: 'na',
    wrongAnswers: ['ni', 'nu', 'ne'],
    lesson: 'Basic Hiragana N Column',
    topic: 'Alphabet',
  },
  {
    character: 'に',
    answer: 'ni',
    wrongAnswers: ['na', 'nu', 'no'],
    lesson: 'Basic Hiragana N Column',
    topic: 'Alphabet',
  },
  {
    character: 'ぬ',
    answer: 'nu',
    wrongAnswers: ['na', 'ni', 'ne'],
    lesson: 'Basic Hiragana N Column',
    topic: 'Alphabet',
  },
  {
    character: 'ね',
    answer: 'ne',
    wrongAnswers: ['na', 'ni', 'no'],
    lesson: 'Basic Hiragana N Column',
    topic: 'Alphabet',
  },
  {
    character: 'の',
    answer: 'no',
    wrongAnswers: ['na', 'ni', 'nu'],
    lesson: 'Basic Hiragana N Column',
    topic: 'Alphabet',
  },
  {
    character: 'は',
    answer: 'ha',
    wrongAnswers: ['hi', 'fu', 'he'],
    lesson: 'Basic Hiragana H Column',
    topic: 'Alphabet',
  },
  {
    character: 'ひ',
    answer: 'hi',
    wrongAnswers: ['ha', 'fu', 'ho'],
    lesson: 'Basic Hiragana H Column',
    topic: 'Alphabet',
  },
  {
    character: 'ふ',
    answer: 'fu',
    wrongAnswers: ['ha', 'hi', 'he'],
    lesson: 'Basic Hiragana H Column',
    topic: 'Alphabet',
  },
  {
    character: 'へ',
    answer: 'he',
    wrongAnswers: ['ha', 'hi', 'ho'],
    lesson: 'Basic Hiragana H Column',
    topic: 'Alphabet',
  },
  {
    character: 'ほ',
    answer: 'ho',
    wrongAnswers: ['ha', 'hi', 'fu'],
    lesson: 'Basic Hiragana H Column',
    topic: 'Alphabet',
  },
  {
    character: 'ま',
    answer: 'ma',
    wrongAnswers: ['mi', 'mu', 'me'],
    lesson: 'Basic Hiragana M Column',
    topic: 'Alphabet',
  },
  {
    character: 'み',
    answer: 'mi',
    wrongAnswers: ['ma', 'mu', 'mo'],
    lesson: 'Basic Hiragana M Column',
    topic: 'Alphabet',
  },
  {
    character: 'む',
    answer: 'mu',
    wrongAnswers: ['ma', 'mi', 'me'],
    lesson: 'Basic Hiragana M Column',
    topic: 'Alphabet',
  },
  {
    character: 'め',
    answer: 'me',
    wrongAnswers: ['ma', 'mi', 'mo'],
    lesson: 'Basic Hiragana M Column',
    topic: 'Alphabet',
  },
  {
    character: 'も',
    answer: 'mo',
    wrongAnswers: ['ma', 'mi', 'mu'],
    lesson: 'Basic Hiragana M Column',
    topic: 'Alphabet',
  },
  {
    character: 'や',
    answer: 'ya',
    wrongAnswers: ['yu', 'yo', 'yi'],
    lesson: 'Basic Hiragana Y Column',
    topic: 'Alphabet',
  },
  {
    character: 'ゆ',
    answer: 'yu',
    wrongAnswers: ['ya', 'yo', 'yi'],
    lesson: 'Basic Hiragana Y Column',
    topic: 'Alphabet',
  },
  {
    character: 'よ',
    answer: 'yo',
    wrongAnswers: ['ya', 'yu', 'yi'],
    lesson: 'Basic Hiragana Y Column',
    topic: 'Alphabet',
  },
  {
    character: 'ら',
    answer: 'ra',
    wrongAnswers: ['ri', 'ru', 're'],
    lesson: 'Basic Hiragana R Column',
    topic: 'Alphabet',
  },
  {
    character: 'り',
    answer: 'ri',
    wrongAnswers: ['ra', 'ru', 'ro'],
    lesson: 'Basic Hiragana R Column',
    topic: 'Alphabet',
  },
  {
    character: 'る',
    answer: 'ru',
    wrongAnswers: ['ra', 'ri', 're'],
    lesson: 'Basic Hiragana R Column',
    topic: 'Alphabet',
  },
  {
    character: 'れ',
    answer: 're',
    wrongAnswers: ['ra', 'ri', 'ro'],
    lesson: 'Basic Hiragana R Column',
    topic: 'Alphabet',
  },
  {
    character: 'ろ',
    answer: 'ro',
    wrongAnswers: ['ra', 'ri', 'ru'],
    lesson: 'Basic Hiragana R Column',
    topic: 'Alphabet',
  },
  {
    character: 'わ',
    answer: 'wa',
    wrongAnswers: ['wo', 'n', 'ra'],
    lesson: 'Basic Hiragana W Column',
    topic: 'Alphabet',
  },
  {
    character: 'ん',
    answer: 'n',
    wrongAnswers: ['wa', 'wo', 'ri'],
    lesson: 'Basic Hiragana W Column',
    topic: 'Alphabet',
  },
  {
    character: 'を',
    answer: 'wo',
    wrongAnswers: ['wa', 'n', 'ro'],
    lesson: 'Basic Hiragana W Column',
    topic: 'Alphabet',
  },
  {
    character: 'が',
    answer: 'ga',
    wrongAnswers: ['gi', 'gu', 'ka'],
    lesson: 'Hiragana K2 Column',
    topic: 'Alphabet',
  },
  {
    character: 'ぎ',
    answer: 'gi',
    wrongAnswers: ['ga', 'gu', 'go'],
    lesson: 'Hiragana K2 Column',
    topic: 'Alphabet',
  },
  {
    character: 'ぐ',
    answer: 'gu',
    wrongAnswers: ['ga', 'gi', 'ge'],
    lesson: 'Hiragana K2 Column',
    topic: 'Alphabet',
  },
  {
    character: 'げ',
    answer: 'ge',
    wrongAnswers: ['ga', 'gi', 'go'],
    lesson: 'Hiragana K2 Column',
    topic: 'Alphabet',
  },
  {
    character: 'ご',
    answer: 'go',
    wrongAnswers: ['ga', 'gi', 'gu'],
    lesson: 'Hiragana K2 Column',
    topic: 'Alphabet',
  },
  {
    character: 'ざ',
    answer: 'za',
    wrongAnswers: ['ji', 'zu', 'ze'],
    lesson: 'Hiragana S2 Column',
    topic: 'Alphabet',
  },
  {
    character: 'じ',
    answer: 'ji',
    wrongAnswers: ['za', 'zu', 'zo'],
    lesson: 'Hiragana S2 Column',
    topic: 'Alphabet',
  },
  {
    character: 'ず',
    answer: 'zu',
    wrongAnswers: ['za', 'ji', 'ze'],
    lesson: 'Hiragana S2 Column',
    topic: 'Alphabet',
  },
  {
    character: 'ぜ',
    answer: 'ze',
    wrongAnswers: ['za', 'ji', 'zo'],
    lesson: 'Hiragana S2 Column',
    topic: 'Alphabet',
  },
  {
    character: 'ぞ',
    answer: 'zo',
    wrongAnswers: ['za', 'ji', 'zu'],
    lesson: 'Hiragana S2 Column',
    topic: 'Alphabet',
  },
  {
    character: 'だ',
    answer: 'da',
    wrongAnswers: ['di', 'du', 'de'],
    lesson: 'Hiragana T2 Column',
    topic: 'Alphabet',
  },
  {
    character: 'ぢ',
    answer: 'ji',
    wrongAnswers: ['da', 'zu', 'do'],
    lesson: 'Hiragana T2 Column',
    topic: 'Alphabet',
  },
  {
    character: 'づ',
    answer: 'zu',
    wrongAnswers: ['da', 'ji', 'de'],
    lesson: 'Hiragana T2 Column',
    topic: 'Alphabet',
  },
  {
    character: 'で',
    answer: 'de',
    wrongAnswers: ['da', 'di', 'do'],
    lesson: 'Hiragana T2 Column',
    topic: 'Alphabet',
  },
  {
    character: 'ど',
    answer: 'do',
    wrongAnswers: ['da', 'ji', 'zu'],
    lesson: 'Hiragana T2 Column',
    topic: 'Alphabet',
  },
  {
    character: 'ば',
    answer: 'ba',
    wrongAnswers: ['bi', 'bu', 'be'],
    lesson: 'Hiragana H2 Column',
    topic: 'Alphabet',
  },
  {
    character: 'び',
    answer: 'bi',
    wrongAnswers: ['ba', 'bu', 'bo'],
    lesson: 'Hiragana H2 Column',
    topic: 'Alphabet',
  },
  {
    character: 'ぶ',
    answer: 'bu',
    wrongAnswers: ['ba', 'bi', 'be'],
    lesson: 'Hiragana H2 Column',
    topic: 'Alphabet',
  },
  {
    character: 'べ',
    answer: 'be',
    wrongAnswers: ['ba', 'bi', 'bo'],
    lesson: 'Hiragana H2 Column',
    topic: 'Alphabet',
  },
  {
    character: 'ぼ',
    answer: 'bo',
    wrongAnswers: ['ba', 'bi', 'bu'],
    lesson: 'Hiragana H2 Column',
    topic: 'Alphabet',
  },
  {
    character: 'ぱ',
    answer: 'pa',
    wrongAnswers: ['pi', 'pu', 'pe'],
    lesson: 'Hiragana H3 Column',
    topic: 'Alphabet',
  },
  {
    character: 'ぴ',
    answer: 'pi',
    wrongAnswers: ['pa', 'pu', 'po'],
    lesson: 'Hiragana H3 Column',
    topic: 'Alphabet',
  },
  {
    character: 'ぷ',
    answer: 'pu',
    wrongAnswers: ['pa', 'pi', 'pe'],
    lesson: 'Hiragana H3 Column',
    topic: 'Alphabet',
  },
  {
    character: 'ぺ',
    answer: 'pe',
    wrongAnswers: ['pa', 'pi', 'po'],
    lesson: 'Hiragana H3 Column',
    topic: 'Alphabet',
  },
  {
    character: 'ぽ',
    answer: 'po',
    wrongAnswers: ['pa', 'pi', 'pu'],
    lesson: 'Hiragana H3 Column',
    topic: 'Alphabet',
  },
  {
    character: 'きゃ',
    answer: 'kya',
    wrongAnswers: ['kyu', 'kyo', 'ka'],
    lesson: 'Hiragana Combinations',
    topic: 'Alphabet',
  },
  {
    character: 'きゅ',
    answer: 'kyu',
    wrongAnswers: ['kya', 'kyo', 'ku'],
    lesson: 'Hiragana Combinations',
    topic: 'Alphabet',
  },
  {
    character: 'きょ',
    answer: 'kyo',
    wrongAnswers: ['kya', 'kyu', 'ko'],
    lesson: 'Hiragana Combinations',
    topic: 'Alphabet',
  },
  {
    character: 'ぎゃ',
    answer: 'gya',
    wrongAnswers: ['gyu', 'gyo', 'ga'],
    lesson: 'Hiragana Combinations',
    topic: 'Alphabet',
  },
  {
    character: 'ぎゅ',
    answer: 'gyu',
    wrongAnswers: ['gya', 'gyo', 'gu'],
    lesson: 'Hiragana Combinations',
    topic: 'Alphabet',
  },
  {
    character: 'ぎょ',
    answer: 'gyo',
    wrongAnswers: ['gya', 'gyu', 'go'],
    lesson: 'Hiragana Combinations',
    topic: 'Alphabet',
  },
  {
    character: 'しゃ',
    answer: 'sha',
    wrongAnswers: ['shu', 'sho', 'sa'],
    lesson: 'Hiragana Combinations',
    topic: 'Alphabet',
  },
  {
    character: 'しゅ',
    answer: 'shu',
    wrongAnswers: ['sha', 'sho', 'si'],
    lesson: 'Hiragana Combinations',
    topic: 'Alphabet',
  },
  {
    character: 'しょ',
    answer: 'sho',
    wrongAnswers: ['sha', 'shu', 'se'],
    lesson: 'Hiragana Combinations',
    topic: 'Alphabet',
  },
  {
    character: 'じゃ',
    answer: 'ja',
    wrongAnswers: ['ju', 'jo', 'ji'],
    lesson: 'Hiragana Combinations',
    topic: 'Alphabet',
  },
  {
    character: 'じゅ',
    answer: 'ju',
    wrongAnswers: ['ja', 'jo', 'ji'],
    lesson: 'Hiragana Combinations',
    topic: 'Alphabet',
  },
  {
    character: 'じょ',
    answer: 'jo',
    wrongAnswers: ['ja', 'ju', 'je'],
    lesson: 'Hiragana Combinations',
    topic: 'Alphabet',
  },
  {
    character: 'ちゃ',
    answer: 'cha',
    wrongAnswers: ['chu', 'cho', 'ci'],
    lesson: 'Hiragana Combinations',
    topic: 'Alphabet',
  },
  {
    character: 'ちゅ',
    answer: 'chu',
    wrongAnswers: ['cha', 'cho', 'ci'],
    lesson: 'Hiragana Combinations',
    topic: 'Alphabet',
  },
  {
    character: 'ちょ',
    answer: 'cho',
    wrongAnswers: ['cha', 'chu', 'ce'],
    lesson: 'Hiragana Combinations',
    topic: 'Alphabet',
  },
  {
    character: 'にゃ',
    answer: 'nya',
    wrongAnswers: ['nyu', 'nyo', 'na'],
    lesson: 'Hiragana Combinations',
    topic: 'Alphabet',
  },
  {
    character: 'にゅ',
    answer: 'nyu',
    wrongAnswers: ['nya', 'nyo', 'nu'],
    lesson: 'Hiragana Combinations',
    topic: 'Alphabet',
  },
  {
    character: 'にょ',
    answer: 'nyo',
    wrongAnswers: ['nya', 'nyu', 'no'],
    lesson: 'Hiragana Combinations',
    topic: 'Alphabet',
  },
  {
    character: 'ひゃ',
    answer: 'hya',
    wrongAnswers: ['hyu', 'hyo', 'ha'],
    lesson: 'Hiragana Combinations',
    topic: 'Alphabet',
  },
  {
    character: 'ひゅ',
    answer: 'hyu',
    wrongAnswers: ['hya', 'hyo', 'hi'],
    lesson: 'Hiragana Combinations',
    topic: 'Alphabet',
  },
  {
    character: 'ひょ',
    answer: 'hyo',
    wrongAnswers: ['hya', 'hyu', 'he'],
    lesson: 'Hiragana Combinations',
    topic: 'Alphabet',
  },
  {
    character: 'びゃ',
    answer: 'bya',
    wrongAnswers: ['byu', 'byo', 'ba'],
    lesson: 'Hiragana Combinations',
    topic: 'Alphabet',
  },
  {
    character: 'びゅ',
    answer: 'byu',
    wrongAnswers: ['bya', 'byo', 'bu'],
    lesson: 'Hiragana Combinations',
    topic: 'Alphabet',
  },
  {
    character: 'びょ',
    answer: 'byo',
    wrongAnswers: ['bya', 'byu', 'be'],
    lesson: 'Hiragana Combinations',
    topic: 'Alphabet',
  },
  {
    character: 'ぴゃ',
    answer: 'pya',
    wrongAnswers: ['pyu', 'pyo', 'pa'],
    lesson: 'Hiragana Combinations',
    topic: 'Alphabet',
  },
  {
    character: 'ぴゅ',
    answer: 'pyu',
    wrongAnswers: ['pya', 'pyo', 'pu'],
    lesson: 'Hiragana Combinations',
    topic: 'Alphabet',
  },
  {
    character: 'ぴょ',
    answer: 'pyo',
    wrongAnswers: ['pya', 'pyu', 'pe'],
    lesson: 'Hiragana Combinations',
    topic: 'Alphabet',
  },
  {
    character: 'みゃ',
    answer: 'mya',
    wrongAnswers: ['myu', 'myo', 'ma'],
    lesson: 'Hiragana Combinations',
    topic: 'Alphabet',
  },
  {
    character: 'みゅ',
    answer: 'myu',
    wrongAnswers: ['mya', 'myo', 'mu'],
    lesson: 'Hiragana Combinations',
    topic: 'Alphabet',
  },
  {
    character: 'みょ',
    answer: 'myo',
    wrongAnswers: ['mya', 'myu', 'me'],
    lesson: 'Hiragana Combinations',
    topic: 'Alphabet',
  },
  {
    character: 'りゃ',
    answer: 'rya',
    wrongAnswers: ['ryu', 'ryo', 'ra'],
    lesson: 'Hiragana Combinations',
    topic: 'Alphabet',
  },
  {
    character: 'りゅ',
    answer: 'ryu',
    wrongAnswers: ['rya', 'ryo', 'ru'],
    lesson: 'Hiragana Combinations',
    topic: 'Alphabet',
  },
  {
    character: 'りょ',
    answer: 'ryo',
    wrongAnswers: ['rya', 'ryu', 're'],
    lesson: 'Hiragana Combinations',
    topic: 'Alphabet',
  },
  {
    character: 'ア',
    answer: 'a',
    wrongAnswers: ['i', 'e', 'u'],
    lesson: 'Basic Katakana Vowels',
    topic: 'Alphabet',
  },
  {
    character: 'イ',
    answer: 'i',
    wrongAnswers: ['a', 'e', 'o'],
    lesson: 'Basic Katakana Vowels',
    topic: 'Alphabet',
  },
  {
    character: 'ウ',
    answer: 'u',
    wrongAnswers: ['a', 'o', 'e'],
    lesson: 'Basic Katakana Vowels',
    topic: 'Alphabet',
  },
  {
    character: 'エ',
    answer: 'e',
    wrongAnswers: ['i', 'o', 'u'],
    lesson: 'Basic Katakana Vowels',
    topic: 'Alphabet',
  },
  {
    character: 'オ',
    answer: 'o',
    wrongAnswers: ['a', 'i', 'u'],
    lesson: 'Basic Katakana Vowels',
    topic: 'Alphabet',
  },
  {
    character: 'カ',
    answer: 'ka',
    wrongAnswers: ['ki', 'ku', 'ko'],
    lesson: 'Basic Katakana K Column',
    topic: 'Alphabet',
  },
  {
    character: 'キ',
    answer: 'ki',
    wrongAnswers: ['ka', 'ku', 'ke'],
    lesson: 'Basic Katakana K Column',
    topic: 'Alphabet',
  },
  {
    character: 'ク',
    answer: 'ku',
    wrongAnswers: ['ka', 'ki', 'ke'],
    lesson: 'Basic Katakana K Column',
    topic: 'Alphabet',
  },
  {
    character: 'ケ',
    answer: 'ke',
    wrongAnswers: ['ka', 'ki', 'ko'],
    lesson: 'Basic Katakana K Column',
    topic: 'Alphabet',
  },
  {
    character: 'コ',
    answer: 'ko',
    wrongAnswers: ['ka', 'ki', 'ku'],
    lesson: 'Basic Katakana K Column',
    topic: 'Alphabet',
  },
  {
    character: 'サ',
    answer: 'sa',
    wrongAnswers: ['shi', 'su', 'so'],
    lesson: 'Basic Katakana S Column',
    topic: 'Alphabet',
  },
  {
    character: 'シ',
    answer: 'shi',
    wrongAnswers: ['sa', 'su', 'se'],
    lesson: 'Basic Katakana S Column',
    topic: 'Alphabet',
  },
  {
    character: 'ス',
    answer: 'su',
    wrongAnswers: ['sa', 'shi', 'so'],
    lesson: 'Basic Katakana S Column',
    topic: 'Alphabet',
  },
  {
    character: 'セ',
    answer: 'se',
    wrongAnswers: ['sa', 'shi', 'so'],
    lesson: 'Basic Katakana S Column',
    topic: 'Alphabet',
  },
  {
    character: 'ソ',
    answer: 'so',
    wrongAnswers: ['sa', 'shi', 'su'],
    lesson: 'Basic Katakana S Column',
    topic: 'Alphabet',
  },
  {
    character: 'タ',
    answer: 'ta',
    wrongAnswers: ['chi', 'tsu', 'to'],
    lesson: 'Basic Katakana T Column',
    topic: 'Alphabet',
  },
  {
    character: 'チ',
    answer: 'chi',
    wrongAnswers: ['ta', 'tsu', 'te'],
    lesson: 'Basic Katakana T Column',
    topic: 'Alphabet',
  },
  {
    character: 'ツ',
    answer: 'tsu',
    wrongAnswers: ['ta', 'chi', 'to'],
    lesson: 'Basic Katakana T Column',
    topic: 'Alphabet',
  },
  {
    character: 'テ',
    answer: 'te',
    wrongAnswers: ['ta', 'chi', 'to'],
    lesson: 'Basic Katakana T Column',
    topic: 'Alphabet',
  },
  {
    character: 'ト',
    answer: 'to',
    wrongAnswers: ['ta', 'chi', 'tsu'],
    lesson: 'Basic Katakana T Column',
    topic: 'Alphabet',
  },
  {
    character: 'ナ',
    answer: 'na',
    wrongAnswers: ['ni', 'nu', 'no'],
    lesson: 'Basic Katakana N Column',
    topic: 'Alphabet',
  },
  {
    character: 'ニ',
    answer: 'ni',
    wrongAnswers: ['na', 'nu', 'ne'],
    lesson: 'Basic Katakana N Column',
    topic: 'Alphabet',
  },
  {
    character: 'ヌ',
    answer: 'nu',
    wrongAnswers: ['na', 'ni', 'no'],
    lesson: 'Basic Katakana N Column',
    topic: 'Alphabet',
  },
  {
    character: 'ネ',
    answer: 'ne',
    wrongAnswers: ['na', 'ni', 'no'],
    lesson: 'Basic Katakana N Column',
    topic: 'Alphabet',
  },
  {
    character: 'ノ',
    answer: 'no',
    wrongAnswers: ['na', 'ni', 'nu'],
    lesson: 'Basic Katakana N Column',
    topic: 'Alphabet',
  },
  {
    character: 'ハ',
    answer: 'ha',
    wrongAnswers: ['hi', 'fu', 'he'],
    lesson: 'Basic Katakana H Column',
    topic: 'Alphabet',
  },
  {
    character: 'ヒ',
    answer: 'hi',
    wrongAnswers: ['ha', 'fu', 'he'],
    lesson: 'Basic Katakana H Column',
    topic: 'Alphabet',
  },
  {
    character: 'フ',
    answer: 'fu',
    wrongAnswers: ['ha', 'hi', 'he'],
    lesson: 'Basic Katakana H Column',
    topic: 'Alphabet',
  },
  {
    character: 'ヘ',
    answer: 'he',
    wrongAnswers: ['ha', 'hi', 'fu'],
    lesson: 'Basic Katakana H Column',
    topic: 'Alphabet',
  },
  {
    character: 'ホ',
    answer: 'ho',
    wrongAnswers: ['ha', 'hi', 'fu'],
    lesson: 'Basic Katakana H Column',
    topic: 'Alphabet',
  },
  {
    character: 'マ',
    answer: 'ma',
    wrongAnswers: ['mi', 'mu', 'mo'],
    lesson: 'Basic Katakana M Column',
    topic: 'Alphabet',
  },
  {
    character: 'ミ',
    answer: 'mi',
    wrongAnswers: ['ma', 'mu', 'me'],
    lesson: 'Basic Katakana M Column',
    topic: 'Alphabet',
  },
  {
    character: 'ム',
    answer: 'mu',
    wrongAnswers: ['ma', 'mi', 'me'],
    lesson: 'Basic Katakana M Column',
    topic: 'Alphabet',
  },
  {
    character: 'メ',
    answer: 'me',
    wrongAnswers: ['ma', 'mi', 'mo'],
    lesson: 'Basic Katakana M Column',
    topic: 'Alphabet',
  },
  {
    character: 'モ',
    answer: 'mo',
    wrongAnswers: ['ma', 'mi', 'mu'],
    lesson: 'Basic Katakana M Column',
    topic: 'Alphabet',
  },
  {
    character: 'ヤ',
    answer: 'ya',
    wrongAnswers: ['yu', 'yo', 'ka'],
    lesson: 'Basic Katakana Y Column',
    topic: 'Alphabet',
  },
  {
    character: 'ユ',
    answer: 'yu',
    wrongAnswers: ['ya', 'yo', 'ki'],
    lesson: 'Basic Katakana Y Column',
    topic: 'Alphabet',
  },
  {
    character: 'ヨ',
    answer: 'yo',
    wrongAnswers: ['ya', 'yu', 'ke'],
    lesson: 'Basic Katakana Y Column',
    topic: 'Alphabet',
  },
  {
    character: 'ラ',
    answer: 'ra',
    wrongAnswers: ['ri', 'ru', 'ro'],
    lesson: 'Basic Katakana R Column',
    topic: 'Alphabet',
  },
  {
    character: 'リ',
    answer: 'ri',
    wrongAnswers: ['ra', 'ru', 're'],
    lesson: 'Basic Katakana R Column',
    topic: 'Alphabet',
  },
  {
    character: 'ル',
    answer: 'ru',
    wrongAnswers: ['ra', 'ri', 'ro'],
    lesson: 'Basic Katakana R Column',
    topic: 'Alphabet',
  },
  {
    character: 'レ',
    answer: 're',
    wrongAnswers: ['ra', 'ri', 'ro'],
    lesson: 'Basic Katakana R Column',
    topic: 'Alphabet',
  },
  {
    character: 'ロ',
    answer: 'ro',
    wrongAnswers: ['ra', 'ri', 'ru'],
    lesson: 'Basic Katakana R Column',
    topic: 'Alphabet',
  },
  {
    character: 'ワ',
    answer: 'wa',
    wrongAnswers: ['wo', 'nn', 'ma'],
    lesson: 'Basic Katakana W Column',
    topic: 'Alphabet',
  },
  {
    character: 'ヲ',
    answer: 'wo',
    wrongAnswers: ['wa', 'nn', 'mo'],
    lesson: 'Basic Katakana W Column',
    topic: 'Alphabet',
  },
  {
    character: 'ン',
    answer: 'nn',
    wrongAnswers: ['wa', 'wo', 'mu'],
    lesson: 'Basic Katakana W Column',
    topic: 'Alphabet',
  },
];
